### DISCUSSION TITLE
Microsoft Word field code/document code insertions

### DISCUSSION THREAD

**Discussion by ZerkerEOD** [espanso/espanso#1162] [Q&A]
**Is your feature request related to a problem? Please describe.**
Would like to create a yml that would act as a cheat sheet for my Word documents. Currently, I have to either copy and paste from a cheat sheet which means having both open. With that said, I use an Elgato stream deck to insert certain field codes by  doing something like CTRL+F9, then typing in the code like 'Client' without quotes, hit F9 again to update, press end to move my curser to behind (since it always ends up at the front of the field code), then space so I can start typing again.

**Describe the solution you'd like**
I am thinking either one of two solutions. Either something specifically for Word to do the above while expanding an entire cheatsheet set of information utilizing the above method.

2nd probably more feasible is to setup and allow for a user-definable macro that could be setup as a param inside expanding text like date.

**Describe alternatives you've considered**
Right now it is just another word document with all my cleared text that I have to go searching through instead of expanding fast by knowing what I am looking for.

**Additional context**
I am unable to think of anything additional as I am not a programmer. This product is great and I would love to see a macro expansion ability. I know it is kinda Niche though but I am sure others could use it.

**Comment by ZerkerEOD** [comment]
Any news on this on potential to insert keyboard characters?

**Comment by ZerkerEOD** [comment]
@federico-terzi, is there a way to move this back to the issues tab and remove it from the discussion and open up the issue and allow me to post a solution that I finally found to get this working with Espanso (and it works great for my use case at least).

**Reply by smeech** [reply]
Sorry this has hung here for a long time.

Would you be happy to post your solution here for consideration?

**Reply by ZerkerEOD** [reply]
@smeech, yeah, it takes a lot of additional research. I basically took a document that was exported as HTML and has my field codes in it and pull. Then I created a filed to be used in all the rest of my code to call it such as {{client}} that was of type echo. Everything uses HTML now and not markdown or standard. I then chip away at parts of where the field is called until I can figure out where it is. Here is the sample for a field called client.

```
global_vars:
  - name: "client"
    type: echo
    params:
      echo: |-
        <!--[if supportFields]><span style='mso-bookmark:_Toc2071405'><span style='mso-bookmark:_Toc535828063'><span style='mso-bookmark:_Toc389724809'></span></span></span><span style='mso-element: field-begin'></span><span style='mso-bookmark:_Toc2071405'><span style='mso-bookmark:_Toc535828063'><span style='mso-bookmark:_Toc389724809'><span style='mso-spacerun:yes'> </span>DOCPROPERTY<span style='mso-spacerun:yes'>  </span>Client<span style='mso-spacerun:yes'>  </span>\* MERGEFORMAT <span style='mso-element:field-separator'></span></span></span></span><![endif]--><span style='mso-bookmark:_Toc2071405'><span style='mso-bookmark:_Toc535828063'><span style='mso-bookmark:_Toc389724809'>CLIENT</span></span></span><!--[if supportFields]><span style='mso-bookmark:_Toc2071405'><span style='mso-bookmark:_Toc535828063'><span style='mso-bookmark:_Toc389724809'></span></span></span><span style='mso-element: field-end'></span><![endif]-->
```

Unfortunately when I started to remove too much, it broke, so I left it as that. When I call, it needs to be an HTML trigger, and I just call it with {{client}}.

For other stuff, using HTML pasted into word works, so for a heading 1 using the <h1></h1> tags works. 

To call Specialized classes you need to search to see how they are setup in your document template. Like we have one called Normal but in the template it is called MsoNormal and I needed to add a style to it for proper formatting. When I call that here is a sample:

```
<p class=MsoNormal style="margin-top: 0;">Insert paragraph data here.</p>
```

The above will format the text with the style of Normal listed above.
