### DISCUSSION TITLE
[Windows] Animated GIFs for Image Match expands to non-animated PNGs

### DISCUSSION THREAD

**Discussion by thamwangjun** [espanso/espanso#1169] [Feature requests and Ideas]
## System Info

Windows Version 10.0.18362 Build 18362
espanso 0.5.2

## Description

Just as the title describes, when an image match for an animated GIF is configured, espanso expands to a non-animated PNG image instead.

**Comment by federico-terzi** [comment]
Hey @tabby-jun ,

Unfortunately, I noticed the same problem a while ago. I still haven't found a way to effectively solve it though, as most programs receive only the CF_BITMAP format, which is not animated...
Source: https://stackoverflow.com/questions/14934327/how-to-get-animated-gif-image-from-browser-clipboard-api

That said, I'll try to find a way to improve the situation and I'll let you know once I find something!

Cheers :)

**Comment by lajlev** [comment]
I experience the same on mac os FB messenger and mac os telegram ✌️

**Comment by federico-terzi** [comment]
@lajlev Thank you for reporting, I still haven't found a reliable way :(

If any of you knows a sequence of steps to paste an animated GIF (for example from google chrome to your chat app of choice) I'd be happy to know :)

**Comment by lajlev** [comment]
Maybe this can be helpful https://github.com/kejadlen/giphy.alfredworkflow

**Comment by federico-terzi** [comment]
@lajlev Interesting, thank you. It seems that the project you've posted simply paste the GIF URL, which is something you can already do with espanso (by using a normal snippet with the URL as replacement) :)

**Comment by tobiasbueschel** [comment]
I've also noticed the same happening on macOS using Slack.

**Comment by j00w33** [comment]
One thing I did was set a script in powershell to set the clipboard to rendered html code:

```yaml
 - trigger: ":smashkeyboard "
    replace: "{{smashkeyboard}}"
    vars:
      - name: smashkeyboard
        type: shell
        params:
          cmd: "Set-Clipboard '<img src=\"https://i.imgur.com/l5AMRPM.gif\" />' -AsHtml"
          shell: powershell
```

This won't paste it in, but it sets the clipboard so that you can manually hit `CTRL+V`  
I'm working an actual script file that will press `CTRL+V` for you but currently the replace portion removes the image right when it shows up.  
If there's a way to just run a command without "replacing" anything then I can probably get it to work.

**Reply by FahadBinHussain** [reply]
any updates?

btw you missed some slashes in your code ig. the correct code is this -

 ```
 - trigger: ":shell"
    replace: "{{output}}"
    vars:
      - name: output
        type: shell
        params:
          cmd: "Set-Clipboard \'<img src=\"https://i.imgur.com/l5AMRPM.gif\" />\' -AsHtml"

```
