### DISCUSSION TITLE
Variable trigger

### DISCUSSION THREAD

**Discussion by Armaldio** [espanso/espanso#1172] [Q&A] [answered]
I have a use case where I need to correct capitalization at the start of a word
It's very common to white like this: HEllo

Is there any way currently to detect that ?

HEllo -> Hello

I think I can do a custom script but the problem remain in the correct trigger

**Comment by federico-terzi** [comment]
Hey @Armaldio ,

At the moment, this is not possible. Would you need it for every possible word or only for a finite number?

Cheers :)

**Comment by Armaldio** [comment]
Indeed every possible word ;)

**Comment by federico-terzi** [comment]
All right, I see. Unfortunately, not possible at the moment :(

**Comment by Armaldio** [comment]
Planned at least ? Or accepting PR ?

**Comment by federico-terzi** [comment]
The biggest problem is that espanso was designed from the ground up with the idea of having known triggers. This feature would require a major rewrite of the espanso core, which is not really advisable at the moment.

I don't exclude the possibility to support this in the future, but at the moment there are a lot to things to do first :)

**Reply by sming** [reply]
Hi @federico-terzi, firstly thank you so much for all your effort with espanso, it’s amazing. To my question: is `:` still essentially hard-coded as the prefix & postfix char? 

I ask since as a coder, I’d like to use espanso in my editors but as you well know, `:` is used an awful lot in programming.

All the best,  Peter

**Comment by Armaldio** [comment]
Understandable.
Anyway, feel free to close or leave open for the future 😃👍

**Comment by federico-terzi** [comment]
I'll keep it open for reference :)

**Comment by smeech** [comment, marked as answer]
Sorry about the late reply - I am trying to mop up and sort the old Issues and Discussions.

This is now fairly straightforward using the shell extension & Regex, e.g.:
```yaml
# Corrects double-capitals typoed at beginnings of words (Linux & ?WSL)
  - regex: (?P<chars>\b[[:upper:]]{2}[[:lower:]])
    replace: "{{output}}"
    vars:
      - name: output
        type: shell
        params:
          cmd: sed -E 's/(.)(.*)/\U\1\L\2/'<<<"$ESPANSO_CHARS"
```

This example is just one of the ways of doing it on Linux, but I would expect could be extended to other OSs.
I'll close this, very old discussion, for now.
