### DISCUSSION TITLE
Create OS-specific matches

### DISCUSSION THREAD

**Discussion by federico-terzi** [espanso/espanso#1174] [Feature requests and Ideas]
This feature would allow the user to select the OSes in which a specific match is valid so that a user could create different matches for each OS, using the same trigger.
This is especially useful when dealing with shell commands or scripts.

This is also somewhat related to #47, so that could be implemented as well in the next release.

**Comment by rflcrz** [comment]
Hi, @federico-terzi.

What about conditional matching? Something similar to PhraseExpress [Conditional statement](https://www.phraseexpress.com/mac/doc/macros/programming/#conditional-statement).

A "condition" could be added under "replace". In this case, a expression could be evaluated as a shell extension. The first "replace" with a valid "condition" would be used.

We would be able to do OS-specific matches _and more_!

Thank you for this great project!

**Comment by federico-terzi** [comment]
Hey @rflcrz,

Thank you for the feedback! Could you please open a separate issue for that? It seems like a cool feature to have :)

Cheers :)

**Comment by risjain** [comment]
I was trying to do the same in order to point to the relative locations of my dotfiles given the OS, for running some scripts.

While many use-cases might be left out, this one works - sort of:

 ```
 - trigger: ":test"
    replace: "{{myshell}}"
    vars:
      - name: WHOME
        type: shell
        params:
           cmd: 'if [[ "$OSTYPE" == "darwin"* ]]; then echo $HOME; elif [[ "$OSTYPE" == "linux-gnu"* ]]; then if [[ `uname -a | grep -i linux | grep -i microsoft`  != "" ]]; then echo /path/to/your/custom/home; fi; fi'
      - name: myshell
        type: shell
        params:
          cmd: "whatever/your/command/is/using/ $ESPANSO_WHOME"
 
```

I tried sourcing the .env file in $HOME - since it will have the basic variables defined - but that didn't work. So, this is the current work around to point to the same custom scripts in both WSL and OSX.

If anyone has a better/cleaner solution - do share!
