### DISCUSSION TITLE
Set expansion property for all matches

### DISCUSSION THREAD

**Discussion by muhlinux** [espanso/espanso#1186] [Feature requests and Ideas]
If you have a user config `/user/spelling.yml`, it would be very convenient to be able to specify global options for that file  making the configuration less repetitive.

```yml
name: spelling
parent: default
propagate_case: true
word: true

matches:
  - trigger: foo  
    replace: bar

  - trigger: baz  
    replace: qux
    propagate_case: false # local overwrite
```
