### DISCUSSION TITLE
[feature] CLI option for fast adding and removing matches

### DISCUSSION THREAD

**Discussion by stheid** [espanso/espanso#1189] [Feature requests and Ideas]
I love `espanso edit`, however when adding triggers on live usage, this is extremely tedious and infeasible.

### i suggest
`espanso add :e:espanso :sh:shorthand` to add the triggers ":e" and ":sh" to the default.yaml
- existing triggers will be skipped with an warning printing the existing match (since this is a shorthand it should not screw up existing matches)
- limitation: the match cannot contain ":" and "," unless they are escaped:   `:tr:"my trigger with colon:"`

`espanso add otherdict :tr:trigger :sh:shorthand` will add a new trigger to "user/otherdict.yaml"
- if otherdict.yaml does not exist it will be created and made child of default.yaml (add "parent: default.yaml" to the file), therefore i dont have to mess arround with my default if i want to create a temporary file
- if it exists we will simply append similarly to the default one, handling duplicates analogously

`espanso rm :tr:trigger :sh:shorthand` removing the two triggers including their options from the default dict.
- triggers with options will trigger an inteactive approval because they cannot be recreated with the sorthand "add"

`espanso rm otherdict :tr:trigger :sh:shorthand` exactly similar as above, however when removing the last trigger, we also remove the file "user/otherdict.yaml"

### limitations
this will only allow to create "simple" triggers, but actually i assume this will already be exremely usefull for the start.
i also think that there could be a syntax to allow providing options. for example one could parse the trigger the following

`:tr:replace(word:true)`
`a:and(word:true)`

This is still a regular expression. we can first consume the () part as a dictionary of additional options. than the first part. With " " we are still able to use parens inside the replacement string.
Although curly braces would be more inuitive i think parens are faster to type and the whole idea of this shorthand is to be able to add new triggers as fast as humanly possible. Since the word option is currently the only useful option one could even compress it further:

`*:tr:replace`
`*a:and`

so if the trigger starts with a * it will enable word matching. Again if the user wants to have a trigger starting with an asterix instead, he could type `"*:tr":trigger`

### final thoughts
right now i am really busy and and i dont know any rust. but would really like to help implementing this feature.
@federico-terzi let me know what you think. i think it would extremely boost the usability for me, as on linux i always have a console arround me with a shortcut.

**Comment by federico-terzi** [comment]
Hey @stheid,

Thank you for the feedback! I like this feature, here are my thoughts:

* I'm not a fan of the `:tr:trigger` syntax. I can see some potential edge cases (some of which you already mentioned) that could cause that method to be unreliable. What about using command line flags? That could be pretty short as well:

```
espanso add -t :tr -r "replace text"
```

This would be pretty easy to parse using [clap](https://github.com/clap-rs/clap), which is the command line arg parser espanso is currently using.

Moreover adding options could be easy as well, for example specifying the "word: true" option.

```
espanso add -t ":es" -r "espanso" -w
```

What do you think about it? That way, we wouldn't need to reinvent the parsing-wheel :)

The biggest issue I see with this feature is that any formatting/comments in the configuration files will be lost. I did some research on this area a few months ago, but there seems to be no comment-preserving YAML parser in Rust.
So as a result, all comments and formatting will be lost when editing. That's not a huge blocker usually, but might be worthy to keep in mind.

Let me know what you think

Cheers :)

**Comment by stheid** [comment]
### general
Hm. I think relieability and implementability are very important considerations. So reinventing the parser wheel would definetly not be good.

On the other hand i think that your proposal would discourage me personally to use this feature, because i could only create one shorthand at a time and its way more syntactic characters which is, imho, the key here.

### implementation ideas
The strings are nearly proper yaml strings: `:tr: trigger` would be directly parsable.

right now i have no smart idea how to deal with that. actually one would _only_ need to extract all _complete_ strings. meaning `:tr:"trig ger"` → [`:tr`, `trig ger`] 

But i also dont know a library that can do that. maybe i can come up with something better, if you are generally interested in using this syntax.

e.g. `espanso add otherdict :tr trigger :sh shorthand *a and` is easily parsable, but might be strange to use (start from the end consuming tuples, if there is one left, thats the file that should be used)

### on commentpreserving
I did not think about that yet... I think if this will remove comments i think it should be stated prominently in the documentation (perhaps in a info box) that manual editing and comments of the file is discouraged.

As i personally would rather use this functionallity for "new" shorthand files i would usually not touch the default.yaml.
I think it should at least be feisable to validate whether comments exist and warn the user (but this obviously adds additionally code).

Overall i think a warning in the documentation and a hint to only use this functionality on completely machine generated files would already be fine. If i followed correctly you are also working on an UI that would anyway screw manually created files, right?

**Comment by federico-terzi** [comment]
> ### general
> Hm. I think relieability and implementability are very important considerations. So reinventing the parser wheel would definetly not be good.
> 
> On the other hand i think that your proposal would discourage me personally to use this feature, because i could only create one shorthand at a time and its way more syntactic characters which is, imho, the key here.

So your main concern would be that my proposal requires to type a command for each new match, am I right?

> ### implementation ideas
> The strings are nearly proper yaml strings: `:tr: trigger` would be directly parsable.
> 
> right now i have no smart idea how to deal with that. actually one would _only_ need to extract all _complete_ strings. meaning `:tr:"trig ger"` → [`:tr`, `trig ger`]
> 
> But i also dont know a library that can do that. maybe i can come up with something better, if you are generally interested in using this syntax.
> 
> e.g. `espanso add otherdict :tr trigger :sh shorthand *a and` is easily parsable, but might be strange to use (start from the end consuming tuples, if there is one left, thats the file that should be used)

My main concern with your syntax is that in order to save a few characters, the whole command becomes less intuitive. If we use a standard UNIX flag-like syntax, that would be very intuitive to use, and you can always create a custom alias/bash function to further speed this up:

```bash
ea () {
  espanso add $1 -t $2 -r $3
}
```

And at that point, you could use:

```
ea otherdict :tr trigger
```

> ### on commentpreserving
> I did not think about that yet... I think if this will remove comments i think it should be stated prominently in the documentation (perhaps in a info box) that manual editing and comments of the file is discouraged.
> 
> As i personally would rather use this functionallity for "new" shorthand files i would usually not touch the default.yaml.
> I think it should at least be feisable to validate whether comments exist and warn the user (but this obviously adds additionally code).
> 
> Overall i think a warning in the documentation and a hint to only use this functionality on completely machine generated files would already be fine. If i followed correctly you are also working on an UI that would anyway screw manually created files, right?

Yes the GUI will not preserve comments and formatting, there is pretty much no way around it other than implementing a parser from scratch (which is really out of the scope at this point).

Let me know what you think

**Comment by stheid** [comment]
Hm, but whould this also easily allow to provide multiple additions at once? **_i assume this is ok and i understand your argumentation_**. I i think finally you have to be convinced as after all its your baby :D

Generally i also agree that consistency of the whole CLI is important and if you think it interferes with the existing structure that is something i can hardly judge.

This script would fully recreate the proposed syntax as a wrapper for your proposed syntax.
```python
from sys import argv
from subproces import run

argv.pop(0)
file = []
if len(argv)//2 == 1:
  file = [argv[0]]
  argv.pop(0)

for i in range(0,len(argv),2):
  wordflag = []
  if argv[i].startswith('*'):
    wordflag = ['-w']
    argv[i] =  argv[i][1:]
  run(['espanso'] + file + ['-t', argv[i], '-r',  argv[i+1]] + wordflag)
```

Running espanso in that way will result in a 𝓞(n²) instead of 𝓞(n) if you only parse yaml once and than add all comments. However this is practically irrelevant i guess, as one would probably never add more than 5 new triggers at a time.

**Comment by federico-terzi** [comment]
Thanks for the help @stheid, indeed your script could be a good solution to this problem. 

I don't think we'll face any performance problem by adding one match at a time, but we can always optimize at that point :)

**Comment by stheid** [comment]
yeah, i just wanted to note it. i find it always helpful to remind oneself about a little complexity theory ;)

**Comment by federico-terzi** [comment]
> yeah, i just wanted to note it. i find it always helpful to remind oneself about a little complexity theory ;)

Of course :)

**Comment by MuhammedZakir** [comment]
How about adding these to another file instead of default.yml? 'espanso-add.yml' or auto or something like that.

**Comment by federico-terzi** [comment]
@MuhammedZakir That might be confusing if done by default, many people only use the `default.yml` file with espanso. That said, that could be easy to achieve with a custom option such as:

```
espanso add "espanso-add" -t "trigger" -r "replacement"
```

Do you see any problem with this approach?

**Comment by MuhammedZakir** [comment]
> That might be confusing if done by default, many people only use the default.yml file with espanso. 

That's true! 

> Do you see any problem with this approach?

Nope! :-) I said it because of issues with comments and I just wanted to type as less as possible. Not that I have any problems with this, but you know...

> espanso add "espanso-add" -t "trigger" -r "replacement"

Is multiple matches in a single command possible with this?

**Comment by federico-terzi** [comment]
> Is multiple matches in a single command possible with this?

As of now, not possible. But when I'll implement this feature I'll make sure to investigate that possibility :)

**Comment by pwujek** [comment]
Would there be any possibility of being able to add simple triggers on the fly, as well as on the command line?

This would allow adding new triggers while typing in text, for example I used to interview people and as they were talking add Microsoft Word replacements as short forms for people's names and departments or acronyms that they referred to which allowed me to keep near verbatim records in real time.

For example entering something along the lines of :myTrigger='my replacement text', and as well as adding myTrigger to the config file it would do the replacement into the current text as well.

**Comment by stratosgear** [comment]
I really like this idea!

Something like this could be done (in a not so elegant way) with something similar to:

```
  - trigger: ":add"
    replace: "{{repl}}"
    vars:
    - name: form1
      type: form
      params:
        layout: |
          Trigger: {{trigger}}
          Replacement: {{replacement}}
    - name: repl
      type: shell
      params:
       cmd: "echo $ESPANSO_FORM1_REPLACEMENT"
```

triggered with `:add`, that pops up a form with a `trigger` textbox and a `replacement` textbox.  My sample implementation does **not** do anything fancy with these two params, but the shell script could append a:

```
  - trigger: "${trigger}"
    replace: "${replacement}"
``` 

section at the end of the ~/.config/espanso/default.yml file.

As I said, hacky and less streamlined than @pwujek suggested, but almost realtime on-the-fly addition of a new replacement.

**Comment by pwujek** [comment]
After posting that comment I realized it might be possible to do it with a trigger.

Here's my non-working trigger - maybe someone could reply with a working version:
```yml
  - trigger: ":new/tr/rp/"
    replace: "$1"
    passive_only: true
    vars:
      - name: output
        type: shell
        params:
          cmd: "echo '  -trigger: \"$0\"\n  replace: \"$1\"\n\n' >> $HOME/.config/espanso/default.yml"

```

**Reply by smeech** [reply]
Late to the game, but as proof of principle, here's working code for adding simple `trigger`/`replace` pairs:
```yaml
  - regex: :new/(?P<trigger>.+)/(?P<replace>.+)/
    replace: "{{output}}"
    vars:
      - name: output
        type: shell
        params:
          shell: bash
          cmd: |
            cat >> $CONFIG/match/my.txt << FIN
              -trigger: {{trigger}}
              -replace: {{replace}}

            FIN
```
Regex triggers probably weren't available when the original question was posed.
I have deliberately left the filename non-`.yml` for testing purposes.
A pop-up GUI with some duplicate- and error-checking would be ideal, though.

**Reply by barnes-b** [reply]
Could potentially add additional shell commands to check for duplicates and/or print out what was added, and put that in {{output}}?

**Comment by federico-terzi** [comment]
@pwujek @stratosgear Thank you for the feedback! Indeed, on-the-fly matches could be very useful. This might be also related to #288.
I'm currently refactoring the core, so this is the best time to consider new features. I created a separate issue: #580

Cheers :)

**Comment by stheid** [comment]
# By the way (as a workarround):
I often have a texteditor open with the default.yaml which i alt-tab into when i need to make a change. Since espanso watches those files its sufficient to save the modified yaml and your shortcuts are available.

**Comment by firinael** [comment]
Bumping this since it's been dead for a while and would be a massive improvement.

**Comment by andyylin** [comment]
Would love to see an easier way to manage triggers as well.

**Comment by smeech** [comment]
There's a (Windows) GUI [in development](https://github.com/Pebkac03/espanso_gui).
I have a Python script here: https://pastebin.com/96RApmkp, to add triggers from the command line, checking for duplicate triggers. I may work it into an Espanso trigger.

**Reply by andyylin** [reply]
Cool, having a Notepad window open to edit the config file is certainly workable, but being able to quickly add a new trigger and replacement would really make the tool much easier to use, and probably expand usage.

**Reply by barnes-b** [reply]
My Espanso triggers for adding matches:


### Simple version (you have to type replacement)
(My understanding is that triggers only fire for things you typed directly, not that you e.g. partly copy-pasted)
```
  - regex: esp;(?P<trigger>..*);(?P<replace>..*);
    replace: "added {{trigger}} -> {{replace}}"
    vars:
      - name: write
        type: shell
        params:
          shell: zsh
          cmd: |
            cat >> "/your_filepath/espanso/match/base.yml" << FIN
              
              - trigger: "{{trigger}}"
                replace: "{{replace}}"
```

### Form (so you can paste replacement)
```
  - regex: esp;(?P<trigger>.*);;
    replace: "added {{trigger}} -> {{form1.replace}}"
    vars:
      - name: form1
        type: form
        params:
          layout: |
            {{trigger}} -> [[replace]]

      - name: write
        type: shell
        params:
          shell: zsh
          cmd: |
            cat >> "/your_filepath/espanso/match/base.yml" << FIN
              
              - trigger: "{{trigger}}"
                replace: "{{form1.replace}}"
```
