### DISCUSSION TITLE
Regex "search and replace" extension

### DISCUSSION THREAD

**Discussion by ansostuhmieng** [espanso/espanso#1198] [Feature requests and Ideas]
One of the most common tasks I do with espanso is trigger scripts that essentially just read from the clipboard, transform the data with a regular expression, and output the data in its new form (I ingest a lot of support requests with partial serial numbers that can be expanded to full ones pretty easily with regex).  It would be fantastic to be able to just write these transforms directly in espanso config documents, making them more portable and making them much more portable to my work colleagues.  I suspect it would result in much faster processing and probably would have a lot of other uses as well.  

I'm thinking a new variable type "regex" that can take in another var as a parameter.  Something like the following (note that the regex is contrived):

```
- trigger: ":expand"
  replace: "{{expanded}}"
  vars:
    - name: "clipboard"
      type: clipboard
    - name: "expanded"
      type: regex
      params:
        search: "([0-9]+)" # Find first number
        replace: "$1" # just keep the number
        input: "clipboard" 

```

Alternately, if the above is not consistent with the flow of espanso parsing, we could just associate search and replace vars with any variable (this actually might be preferred as it requires a lot less configuration).  The following is the example above with this simplification in place - probably a more elegant solution.  

```
- trigger: ":expand"
  replace: "{{clipboard}}"
  vars:
    - name: "clipboard"
      type: clipboard
      params:
        search: "([0-9]+)" # Find first number
        replace: "$1" # just keep the number
```

If params is the wrong place, then a more capable "transforms" element could be added, taking in a type.  This would allow for regex or string replacement, as well as potential expansion in the future for more types. 

```
- trigger: ":expand"
  replace: "{{clipboard}}"
  vars:
    - name: "clipboard"
      type: clipboard
      transform:
        type: regex
        search: "([0-9]+)" # Find first number
        replace: "$1" # just keep the number
- trigger: ":expand2"
  replace: "{{clipboard}}"
  vars:
    - name: "clipboard"
      type: clipboard
      transform:
        type: text
        search: "A" # Find any instance of A
        replace: "B" # Replace it with B
```

**Comment by federico-terzi** [comment]
Hey @ansostuhmieng,

Thank you for the feedback! I can see how this feature would be useful, so I'll happily consider it for the next versions. I'll investigate about the easiest (and most elegant) way to include it in espanso without changing the core.
Most likely, this will end up as another Match extension.
Keep the notifications open for this one, I'll let you know once we have something to try out

Cheers :)

**Comment by ansostuhmieng** [comment]
@federico-terzi Thanks for your response and the excellent application :)  Switching to it took a bit of work but it has been well worth it.

**Comment by federico-terzi** [comment]
Thanks for the kind words! I'm glad espanso fits your needs

**Comment by katrinleinweber** [comment]
Related request, maybe an intermediate step towards full support of such a `search:` & `replace:` match extensions: Supporting the insertion of `{{clipboard}}` and variables in a script's `params:`/`args:` section.

My usecase is similar to @ansostuhmieng's: formatting Markdown links with the URL in the clipboard and calling 2 scripts to retrieve/format a `title` and an `id`.

```
  - trigger: "[''"
    replace: "[{{id}}]({{clipboard}})"
    vars:
      - name: id
        type: script
        params:
          args:
            - bash
            - "%CONFIG%/scripts/get-id.sh"
            - "{{clipboard}}"
```

Currently, this results in `[({{clipboard}})](https://…as…expected…)`, showing that the clipboard _content_ is inserted only within `replace:`.

On macOS, I also tested `pbpaste` as the 3rd argument, but that results in `[pbpaste](https://…as…expected…)`.

---

The script contains `echo "$1" | sed … | sed …`, so I'm also wondering whether a `search:` & `replace:` match extensions could also be chained?

---

In either case: Great tool :-)

**Comment by federico-terzi** [comment]
Hey @katrinleinweber,

Thank you for the feedback! I think your use-case could be already solved with a bit of bash gymnastic, something like this (not tested):

```yaml
  - trigger: "[''"
    replace: "[{{id}}]({{clipboard}})"
    vars:
      - name: clipboard
        type: clipboard
      - name: id
        type: script
        params:
          args:
            - bash
            - "%CONFIG%/scripts/get-id.sh"
```

And then in the `get-id.sh` file, you should be able to read the `$ESPANSO_CLIPBOARD` env variable

```bash
#!/bin/bash

echo $ESPANSO_CLIPBOARD
```

For more information, see this section of the docs: https://espanso.org/docs/matches/#advanced-topics

Let me know if that helps!

Cheers :)
