### DISCUSSION TITLE
Support multiple line selections in form list

### DISCUSSION THREAD

**Discussion by federico-terzi** [espanso/espanso#1199] [Feature requests and Ideas]
Pasting a user request:

I’m running into a limitation with forms and wanted to see if the answer exists. Below is some example code. Ignore any bad formatting. I’m on mobile. I want the ability to select and arbitrary number of choices. In some cases I might need first choice. Sometimes I’ll need second choice and fourth choice. I might even need all of the four choices.

As far as I can tell, with type:list you can only select a single choice. Is there another type of form that lets you select multiple choices, or perhaps another parameter for the form?

```
- trigger: ":form"
form: |
  {{choices}}
form_fields:
  choices:
    type: list
    values:
      - First choice
      - Second choice
      - Third choice
      - Fourth choice
```

**Comment by CountCypher** [comment]
I'd love to have that feature as well. 
My use case: We use espanso to create a little text block for a meeting protocol which states the date and the attendees at the beginning, among other things. With a multi select choice box I could easily pick the attendees to be filled in.

Btw, thanks a lot for your work on this great tool. Couldn't live without it!

**Reply by lumetrium** [reply]
It's been a long time, but if you're still interested in this feature, please check out [Espanso Dynamic Forms](https://github.com/lumetrium/espanso-dynamic-forms).

**Comment by federico-terzi** [comment]
@CountCypher Thanks for the kind words and the useful insight! Hopefully, in one of the next releases, I'll be able to add it :)

**Comment by emilBeBri** [comment]
Hi, how is it going with this? I would love this as well!

**Comment by Ducesaro** [comment]
Hello, as a van? I think I have the answer and it is that I currently manage forms with drop-down lists where I can select any box to do so, I show you the configuration I have and I hope it can help you
```yml
  - trigger: "* 92"
    replace: "{{form1.name}};{{form1.name1}};{{form1.name2}};{{form1.fruit}};{{form1.name4}}"
    vars:
      - name: form1
        type: form
        params:
          layout: |-
            Número de celular a borrar: [[name]] 
            Cedula a borrar: [[name1]]
            Número donde el cliente se va a registrar: [[name2]]
            Estado (Normal o retirado): [[fruit]]
            Saldo: [[name4]]
          fields:
            name:
              multiline: false
            name1:
              multiline: false
            fruit:
              type: choice
              values:
                - Normal
                - Retirado
```

**Comment by Ducesaro** [comment]
![image](https://user-images.githubusercontent.com/103975779/188229532-1be45966-f1ab-4c78-ad46-dfb3754e919c.png)

**Comment by Ducesaro** [comment]
This is another setup I have. I hope it works for you

![image](https://user-images.githubusercontent.com/103975779/188229859-637dc387-d9d0-430f-b123-db3cd5404758.png)

**Comment by saif-ellafi** [comment]
Hi, I would like to add my vote to support multiple selection (with CTRL+CLICK) in type `list`
My use case is to be able to concatenate all the selected values and form a sentence made by the choices.

Edit: My current workaround is to repeat the form field many times, but it looks ugly :)

Thanks for the awesome espanso

**Comment by emilBeBri** [comment]
Hi I’ve made a script that solves this by moving the selection into a bash script instead -  only tested on my Manjaro linux box. It uses rofi as input selector, but dmenu or fzf would work too:

```
#!/bin/bash
# list-selector.sh
# set euo pipefail

# input either a file or something from a pipe
[ $# -ge 1 -a -f "$1" ] && var1="$1" || var1="-"



# var1="$1"
var1=$(cat $var1)


# theregex='[^0-9](\d{1,1})[^0-9]'
# var1=$(
#     cat /home/emil/Dropbox/share/qutebrowser/in-use/bookmarks/urls | rg -o " #\w*-*\w*" |  sort -k2       | uniq  -c | rg  --replace '0$1 '  --passthru --no-line-number "$theregex" | sort -r | rg -o '\d+.*' | 
#     # remove double whitespace
#     sed -r 's/[[:space:]]+/ /g' 
#     )
# # lolecho "$var1"




tags1=$(mktemp)

still_choosing=1



while ((  $still_choosing == 1 )); do
    # lolecho "$still_choosing"


    tmp2=$(mktemp)
    # cat "$1"  > $tmp2
    echo "$var1"  > $tmp2
    # lolcat "$tmp2"


    # if it;s the first the loop runs, just show the entire list
    if [[ -z $(grep '[^[:space:]]' $tags1) ]] ; then

        # choice1=$(cat /home/emil/Dropbox/todo/todo.txt | rg -o "\+\w+" | sort | uniq | rofi -dmenu -i  -p "tekst" -matching normal -sort -sort-method fuzzy)

      choice1=$(echo "$var1" | rofi -dmenu -i  -p "Project:" -matching normal -sort -sort-method fuzzy)
      # choice1=$(cat "$var1" | rofi -dmenu -i  -p "Project:" -matching normal -sort -sort-method fuzzy)
      # lolecho "$choice1"

    # if not, only show the tags that are not already chosen
     else 



      choice1=$(awk 'NR==FNR{++a[$0]} !a[$0]' $tags1 $tmp2  | rofi -dmenu -i  -p "Project" -matching normal -sort -sort-method fuzzy)

     # cat $tags1
     # cat $tmp2
    fi

# if a choice has been made, append it to the tags file
  if [[ ! -z $(echo "$choice1" | grep '[^[:space:]]' ) ]] ; then


    echo $choice1 >> $tags1

    # restart the loop
    still_choosing=1
    choice1=$(echo '')

   else 

    still_choosing=0

  fi


done

cat "$tags1"




```
put that in your $HOME/bin directory (or where ever else you want in from your $PATH) and then you can use it like this with espanso:

```
  - trigger: ";test"
    replace: "{{output}}"
    vars:
      - name: "output"
        type: shell
        params:
          cmd: 'echo -e "choice A\nchoiceB\nchoice C\nchoice D" | $HOME/bin/list-selector.sh'

```
