### DISCUSSION TITLE
Macro support

### DISCUSSION THREAD

**Discussion by federico-terzi** [espanso/espanso#1201] [Feature requests and Ideas]
Many text expanders support multi-step expansions. For example, a macro could look like:

* Insert "hello@example.com"
* Press Tab
* Wait 300ms
* Insert "Hey {{name}}"

This could be used to automate form fillings, bookmarks and many more

Related #286

**Comment by sidouglas** [comment]
Prioritise #420. 😉

**Comment by federico-terzi** [comment]
@sidouglas #420 is definitely on top of my priorities :)

**Comment by reesericci** [comment]
I need this!

**Comment by ghost** [comment]
@reesericci You could do that right now by using https://github.com/Lexikos/AutoHotkey_L

It's a macro creation tool, happy scripting

**Comment by reesericci** [comment]
I love Autohotkey, I wish I could use it. But now I'm on Linux, and AHK doesn't work on Linux. I've used it and its awesome.

**Reply by vhermecz** [reply]
For Linux you have https://github.com/autokey/autokey
But, having a cross platform solution for this would be really awesome

**Comment by vasko-deb** [comment]
Definitely! Yes, pls!

**Comment by j00w33** [comment]
We got any update on this? It looks to have been moved to a Discussion rather than an issue.  
Are there technical limitations preventing this? I know wayland is weird about Macros, but X supports it quite well

**Comment by bellicose100xp** [comment]
Any updates. I would definitely love to see this.

**Comment by ghost** [comment]
@federico-terzi is it implemented? could not find it in the documentation

**Reply by federico-terzi** [reply]
Nope! Didn't have the chance to implement it yet :)

**Comment by smeech** [comment]
The first step might be finding a way of introducing a delay in the middle of a `replace:` string. We have the other steps you listed above, and I use them to complete occasional forms.

AutoHotKey is, of course, much more sophisticated in this regard, and can use more precise controls than TABs and delays, by explicit identification of menu-items and form fields by name, and the generation of ALT- and CTRL-keys to navigate menus. However, Espanso meets most of my needs as a replacement!

**Reply by kengribble** [reply]
Maybe a way to introduce %%functions%% that can be used like:

replace: "This needs a delay before return is hit:%%wait 5ms%%\n"

I just pulled %% out of a hat, I don't know what would be better.

Other possible functions (that I haven't looked up to see if they are needed):

%%direction key [lrud]%% — uses arrow keys on keyboard for left, right, up, down.
%%backspace%% — simple backspace (maybe this is supported already in another form, like \b?)
%%functionkey [1-12]%% — hits a function key
%%esc[ape]%% — escape key

**Comment by Kaushik-Rajarathinam** [comment]
I need arrow key presses, is that available on Espanso??

**Reply by smeech** [reply]
No - Espanso only inputs characters that have ASCII values as triggers. The only non-text keys I've found are [\<ctrl-key\> combinations](https://espanso.org/docs/matches/basics/#keyboard-triggers).
For output, you'd have to use something like xdotool in a shell extension, e.g.: `cmd: xdotool key Left Left Left` but that interferes with deletion of the original trigger characters.

**Comment by at-ng** [comment]
As a workaround for Windows users, you can do this

```
  - trigger: ":kp"
    replace: "{{output}}"
    vars:
      - name: output
        type: shell
        params:
           shell: powershell
           cmd: (New-Object -ComObject wscript.shell).SendKeys('{F5}')
```

To trigger a F5 kepress when you type :kp, see [this page](https://learn.microsoft.com/en-us/office/vba/language/reference/user-interface-help/sendkeys-statement) for examples for what you can use instead of F5, multiple keys works as well. For delays the cmd would be something like:

```
(New-Object -ComObject wscript.shell).SendKeys('{BACKSPACE}{BACKSPACE}{BACKSPACE}abc'); Start-Sleep -Seconds 1.5; (New-Object -ComObject wscript.shell).SendKeys('123...')
```
({BACKSPACE} x3 and ... is because espanso tries to remove three characters after the script command has executed so this compensates for that)

**Reply by berot3** [reply]
That's a nice workaround, thank you so much for sharing!

**Comment by smeech** [comment]
I have a pair of scripts, https://pastebin.com/c4QHdnc8 & https://pastebin.com/KKX8GPzD, which do something very similar using `xdotool`.

**Reply by smeech** [reply]
> I have a pair of scripts, https://pastebin.com/c4QHdnc8 & https://pastebin.com/KKX8GPzD, which do something very similar using `xdotool`.

I have published the scripts, which should work in all OSs that have Python installed, as a [package](https://github.com/espanso/hub/tree/main/packages/delays-characters/0.1.0) although for some reason it's not appaearing in the Hub yet.

Install with `espanso install delays-characters`.

**Comment by reagle** [comment]
For those on MacOS, you can install and use clicklick.

```
  - trigger: ":regex_test"
    replace: "{{output}}"
    vars:
      - name: output
        type: shell
        params:
          cmd: '/opt/homebrew/bin/cliclick t:"(<ref\b[^>]*?)(/>|>.*?<\/ref>)\." w:200 kp:tab w:200 t:".\1\2" w:200'
  - trigger: ":regex_broken"
    # this doesn't work as it types the tab before the other two strings
    replace: "{{find}}{{tab}}{{replace}}"
    vars:
      - name: find
        type: echo
        params:
          echo: '(<ref\b[^>]*?)(/>|>.*?<\/ref>)\.'
      - name: tab
        type: shell
        params:
          cmd: "/opt/homebrew/bin/cliclick w:500 kp:tab w:500"
      - name: replace
        type: echo
        params:
          echo: '.\1\2'
```
