### DISCUSSION TITLE
Extend `random` to support images

### DISCUSSION THREAD

**Discussion by iRomanyshyn** [espanso/espanso#1212] [Feature requests and Ideas]
Hi! I tried to do this:

```
  - triggers: [":choose", ":choice"]
    image_path: "{{output}}"
    vars:
      - name: output
        type: random
        params:
          choices:
            - "$CONFIG/user/choice1.jpg"
            - "$CONFIG/user/choice2.jpg"
            - "$CONFIG/user/choice3.jpg"
            - "$CONFIG/user/choice4.png"
```

But it just replaces trigger with nothing.

**Comment by federico-terzi** [comment]
Hey @iRomanyshyn,

Thank you for the feedback! Unfortunately, this is not yet possible, but we can keep this issue open as a feature request!

Cheers :)

**Comment by tobiasbueschel** [comment]
This would be a great feature to have, one use case I have for this:

- I keep a folder with my favorite memes
- Adding an expansion for `:meme` picks a random image from the folder

It would also be great to add image support for `type: choice`, e.g. using the following:

```yml
matches:
  - trigger: ":meme"
    replace: "{{output}}"
    vars:
      - name: output
        type: choice
        params:
          values:
            - image_path: "$CONFIG/images/some_random_meme.jpg"
              id: "Title of random meme"
              preview: true
            - image_path: "$CONFIG/images/another_meme.jpg"
              id: "Title of second meme"
```

And one could add `preview: true` to show a rich preview of the image in the Espanso search overlay.

**Comment by federico-terzi** [comment]
@tobiasbueschel Thank you for the feedback!

**Comment by tobiasbueschel** [comment]
@iRomanyshyn this is the work around I am currently using (don't mind the image names) - it's not randomly selected, but perhaps might help too.

```yml
matches:
  - trigger: ":meme"
    image_path: "$CONFIG/images/unit_tests_we_dont_do_that_here.jpg"
  - trigger: ":meme"
    image_path: "$CONFIG/images/why_wont_they_merge_my_pull_request.png"
  - trigger: ":meme"
    image_path: "$CONFIG/images/thy_commit_shall_pass.jpg"
```

@federico-terzi more than happy to, would also be keen to contribute, if only I would know Rust :D

Is there any attribute such as `id` or `name` that I can set on these matches so that the search shows a description instead of `Image content`?

<img width="546" alt="Screen Shot 2022-03-28 at 1 07 49 AM" src="https://user-images.githubusercontent.com/13087421/160292512-2060704f-c9e1-420d-8605-cfac93c4f44e.png">
 
An alternative, yet less user-friendly option could be to call e.g., a Node.js / Python script and randomly return an image.

---

**EDIT:** 

The following **is not valid at the moment**, but it might be nice if the `image_path` could take an array of images:
```yml
matches:
  - trigger: ":meme"
    image_path:
      - "$CONFIG/images/unit_tests_we_dont_do_that_here.jpg"
      - "$CONFIG/images/why_wont_they_merge_my_pull_request.png"
      - "$CONFIG/images/thy_commit_shall_pass.jpg"
```
