### DISCUSSION TITLE
Allow for a optional delay before replacing text

### DISCUSSION THREAD

**Discussion by adgai19** [espanso/espanso#1238] [Feature requests and Ideas]
Not a super priority but think it could be useful for setting up tree like mappings. For example
`e` could expand to `export`
`ed` could expand to `export default`
`edc` could expand to `export default class`
`edf` could expand to `export default function`
I have been using espanso for only about a day now, so I don't know if this is already possible. Great job writing it though

**Comment by federico-terzi** [comment]
Hey @adgai19,

Thank you for the feedback! This seems to be related to #663, I'll mark it as a feature request

Cheers :)

**Comment by federico-terzi** [comment]
@adgai19 In the meanwhile, you might be able to get a similar behavior with the "word" option:

```yaml
  - trigger: "ed"
    replace: "export default"
    word: true
  - trigger: "edc"
    replace: "export default class"
    word: true
```

This way, it will wait for a word delimiter before expanding (such as a space or period), and you have the time to choose either `ed` or `edc`

See also: https://espanso.org/docs/matches/#word-triggers
