### DISCUSSION TITLE
Add fish to the possible values for the shell parameter for MacOS

### DISCUSSION THREAD

**Discussion by ghost** [espanso/espanso#1244] [Feature requests and Ideas]
**Is your feature request related to a problem? Please describe.**
I'm trying to run a shell command, but it's saying command not found. I'm assuming this is because while zsh is the default shell for mac, [it is not one of the possible options to choose as a shell in espanso.](https://espanso.org/docs/matches/#shell-extension)

**Describe the solution you'd like**
Add zsh to the possible values for the shell parameter for MacOS

**Describe alternatives you've considered**
I could change my terminal to bash and then reinstall all my shell packages in bash, but that's not really optimal (bash is old and deprecated on mac due to licensing).

**Comment by federico-terzi** [comment]
Hey @nogira,

Thank you for the feedback! Sounds definitely reasonable, I'll add it to the roadmap :)

Cheers :)

**Comment by kmplngj** [comment]
I would like to see fish.

Thanks
Jan

**Comment by ghost** [comment]
if you need a workaround for fish until it's added, here is an example of running the `status filename` fish command

```yaml
  - trigger: test
    replace: "{{output}}"
    vars:
      - name: output
        type: shell
        params:
          cmd: fish -c "status filename"
          shell: zsh
```
