### DISCUSSION TITLE
Insert same value in multiple places in form

### DISCUSSION THREAD

**Discussion by shbach** [espanso/espanso#1263] [Q&A] [answered]
**Is your feature request related to a problem? Please describe.**
Previously mentioned [here](https://www.reddit.com/r/espanso/comments/tc5elr/insert_same_value_in_multiple_places_in_form/).

I want to be able to insert the same value multiple times in a form e.g.  to insert a template set of tasks using [todo.txt format](https://github.com/todotxt/todo.txt):

```
- trigger: ":project"
   form: |
      (A) task 1 +{{project_name}}
      (C) task 2 +{{project_name}}
      (C) task 3 +{{project_name}}
      (C) task 4 +{{project_name}}
```

Currently when I do this the form will have multiple input boxes for `{{project_name}}` for which only the last box will be valid. I want to have only one box appear in the form.

**Describe the solution you'd like**
One way to possibly make this work is to be able to define a question and have exact matches contained within `{{}}` be replaced. For the above example I could set up a question like "What is the project name?" and the form would allow me to input the value which is then replaced anywhere with `{{project_name}}`

**Comment by federico-terzi** [comment]
Hey @shbach,

Thank you for the feedback! I'll add it to the roadmap

Cheers :)

**Reply by RicoLaaa** [reply]
Hi,

has any development been done on this feature? I'm trying to achieve similar results in a form where I ask for a date in a input field, and the date is printed again in another sentence of the same form.

cheers

@federico-terzi thanks for the great work on this tool, just discovered it and it's saving me loads of time at work 🙏🏻

**Comment by kpym** [comment, marked as answer]
@shbach You can use the form as a variable like this:
```yaml
  - trigger: ":project"
    replace: |
      (A) task 1 +{{project.name}}
      (C) task 2 +{{project.name}}
      (C) task 3 +{{project.name}}
      (C) task 4 +{{project.name}}
    vars:
      - name: project
        type: form
        params:
          layout: Project [[name]]
```
