### DISCUSSION TITLE
Implement prioritization/ranking in search bar results

### DISCUSSION THREAD

**Discussion by revolter** [espanso/espanso#1274] [Feature requests and Ideas]
**Describe the bug**

The search window prioritizes the replacement instead of the trigger.

**To Reproduce**

1. Add this to the `base.yml` file:

```yml
matches:
  - trigger: "test"
    replace: "tested"

  - trigger: "tested"
    replace: "test"
```
2. Open the search window
3. Search for `test`

**Expected behavior**

![image](https://user-images.githubusercontent.com/5748627/170958745-2464219d-d119-4104-a4ed-115d846a9418.png)

**Actual behavior**

![image](https://user-images.githubusercontent.com/5748627/170958817-f9dd2310-e896-43d1-aab5-280e5373b546.png)

**Screenshots**

**Logs**

**Setup information**
- OS: macOS 12.3.1 (21E258)
- Version: espanso 2.1.5-beta
