### DISCUSSION TITLE
ANSWERED: Does Random support multiline replies (using folded block scalar)?

### DISCUSSION THREAD

**Discussion by clivemeister** [espanso/espanso#1309] [Q&A] [answered]
It doesn't seem like we can have multiline replies (using the folded block scalar '>') with the Random extension:
matches:
```
# this works
  - trigger: ":works"
    replace: "{{output}}"
    vars:
      - name: output
        type: random
        params:
          choices:
            - "long line of text that I want to split over two file lines"
            - "another long line of text that I want to enter over two lines for readability"

# this doesn't work
  - trigger: ":doesnotwork"
    replace: "{{output}}"
    vars:
      - name: output
        type: random
        params:
          choices:
            >
             long line of text
             that I want to split over two file lines
           >
             another long line of text that I want to enter 
             over two lines for readability
```
I get an error on the second block.  Does this work for others, with some small tweak I'm missing?

**Comment by kpym** [comment, marked as answer]
For me it works, but you have to put `-` before the choices, like this:
```yaml
  - trigger: ":nowitworks"
    replace: "{{output}}"
    vars:
      - name: output
        type: random
        params:
          choices:
            - >
             long line of text
             that I want to split over two file lines
            - >
             another long line of text that I want to enter
             over two lines for readability
```
