### DISCUSSION TITLE
Grouping matches & common prefixes/suffixes

### DISCUSSION THREAD

**Discussion by krystof-k** [espanso/espanso#1318] [Feature requests and Ideas]
I'm coming from aText which has a nice feature of adding common prefix for a group of matches. I kind of like the straightforwardness of Espanso, one record, one match, but maybe it would be an interesting feature for tidying up the configs.

It could look like this for example:

```yaml
groups:
  arrows: # group
    trigger:
      suffix: arrow
    matches:
      - trigger: left # expands on leftarrow
        replace: ←
      - trigger: right # expands on rightarrow
        replace: →
```
