### DISCUSSION TITLE
Multiple characters dynamic replacement: 123superscript → ¹²³

### DISCUSSION THREAD

**Discussion by krystof-k** [espanso/espanso#1319] [Q&A] [answered]
I was trying to play around with regexes and variables, but I couldn't figure out how to achieve this. There definitely has to be a solution using some scripting, but I'm curious whether there is a way how to achieve this without it.

The goal is to expand `123subscript` or `456789superscript` (unlimited number of digits) to their sub/superscript variants.

Currently I have the following config:

<details open>
<summary>`sub-superscript.yml`</summary>

```yaml
matches:
  - trigger: 0subscript
    replace: ₀
  - trigger: 0superscript
    replace: ⁰
  - trigger: 1subscript
    replace: ₁
  - trigger: 1superscript
    replace: ¹
  - trigger: 2subscript
    replace: ₂
  - trigger: 2superscript
    replace: ²
  - trigger: 3subscript
    replace: ₃
  - trigger: 3superscript
    replace: ³
  - trigger: 4subscript
    replace: ₄
  - trigger: 4superscript
    replace: ⁴
  - trigger: 5subscript
    replace: ₅
  - trigger: 5superscript
    replace: ⁵
  - trigger: 6subscript
    replace: ₆
  - trigger: 6superscript
    replace: ⁶
  - trigger: 7subscript
    replace: ₇
  - trigger: 7superscript
    replace: ⁷
  - trigger: 8subscript
    replace: ₈
  - trigger: 8superscript
    replace: ⁸
  - trigger: 9subscript
    replace: ₉
  - trigger: 9superscript
    replace: ⁹
```

</details>

My idea was to create some regex `\d+(sub|super)script` with capture groups and then expand the appropriate match for each digit.

Any thoughts? :)

**Comment by kpym** [comment]
You can use `regex` to pass the numbers as parameter, then use a script to translate them. Unfortunately `tr` is not compatible with unicode, but we can use `sed` for this.
 
```yaml
  - regex: ":(?P<num>\\d+)_"
    replace: "{{sub}}"
    vars:
      - name: sub
        type: shell
        params:
          cmd: echo $ESPANSO_NUM | sed -e 'y/0123456789/₀₁₂₃₄₅₆₇₈₉/'
          shell: wsl
```
If you do not use Windows, you should remove `shell: wsl`.
So by typing `:123_` you get `₁₂₃`.

**Reply by krystof-k** [reply]
That is a great approach, thank you.

However it is not working on macOS for me, because of some issue with Unicode:

```
10:25:28 [worker(17078)] [ERROR] shell command exited with code: exit status: 1 and error: sed: 1: "y/0123456789/₀₁₂� ...": transform strings are not the same length

10:25:28 [worker(17078)] [WARN] extension 'shell' on var: 'result' reported an error: command reported error: '`sed: 1: "y/0123456789/₀₁₂� ...": transform strings are not the same length
`'
10:25:28 [worker(17078)] [ERROR] error during rendering: rendering error

Caused by:
    command reported error: '`sed: 1: "y/0123456789/₀₁₂� ...": transform strings are not the same length
    `'
```

I'll try to look deeper into that.

**Reply by krystof-k** [reply, marked as answer]
OK, got this. I needed to set `LANG` variable first.

Here is my final config:

```yaml
  - regex: '(?P<number>\d+)(?P<type>(sub|super)script)'
    replace: '{{ result }}'
    vars:
      - name: result
        type: shell
        params:
          cmd: |
            export LANG='cs_CZ.UTF-8'
            if [[ "$ESPANSO_TYPE" == "superscript" ]]; then
              echo "$ESPANSO_NUMBER" | sed -e 'y/0123456789/⁰¹²³⁴⁵⁶⁷⁸⁹/'
            else
              echo "$ESPANSO_NUMBER" | sed -e 'y/0123456789/₀₁₂₃₄₅₆₇₈₉/'
            fi
```

Thanks again!
