### DISCUSSION TITLE
use files as source for "replace:"

### DISCUSSION THREAD

**Discussion by berot3** [espanso/espanso#1323] [Feature requests and Ideas]
Hey everyone!

I'd like to espanso, but one thing is hidnering me to use it as my main tool.

Szenario: All my textes that I want to insert (aka what goes after `replace:`) are all in their own file.

Example: for trigger `:br` my text that I want to use is in br.txt.

So what I would like to do is the following match:

```
- trigger: ":br"
  replace: /path/to/br.txt
```

**Comment by berot3** [comment]
oh, my bad, I think this is basically the same as #1215

Is there maybe some other way to get the same result? Possibly with a python-script or similar?

**Reply by smeech** [reply]
Just mopping up some old discussions.

I think this is possible with some code such as:
```  
  - trigger: :test
    replace: "{{output}}"
    vars:
      - name: output
        type: shell
        params:
          cmd: echo $(</path/to/br.txt)
```
