### DISCUSSION TITLE
Simplify syntax for Choice and Random Extensions

### DISCUSSION THREAD

**Discussion by e-r-n-i-e** [espanso/espanso#1360] [Feature requests and Ideas]
It would be nice to have a common syntax for the Random and the Choice Extension. That means the Random Extension should additionally accept `values` as a synonym for `choices` as parameter name. Like so:

```
  - trigger: "choice#"
    replace: "{{output}}"
    vars:
      - name: output
        type: choice
        params:
          values:
            - "I love Espanso"
            - "I like Espanso"

  - trigger: "random#"
    replace: "{{output}}"
    vars:
      - name: output
        type: random
        params:
          values:
            - "I love Espanso"
            - "I like Espanso"
```

This would make it easier to switch from random selection to menu and the syntax would be easier to remember. What do you think?
