### DISCUSSION TITLE
WSL compatible script path references using %CONFIG% in the path for wsl scripts

### DISCUSSION THREAD

**Discussion by eprosimon** [espanso/espanso#1378] [Feature requests and Ideas]
From the docs it is recommended to use %CONFIG% part of the path, as shown in the example below: 

```
      - name: output
        type: script
        params:
          args:
            - wsl
            - "%CONFIG%/scripts/script.sh"
```
This works great on Mac for sh scripts and works on windows for powershell. 
On Windows I have been running into an issue where %CONFIG% will output a 'Windows style path' even when the args mentions 'wsl'  like C:\User\username\AppData...etc then tack on the /scripts/script.sh 

This ends up being an invalid path for WSL and throws an error (path cant be found)

WSL path vs windows path:
/mnt/c/User/Erich  = C:\User\Erich

hardcoding the path for the specific user with a wsl compatible path does run the script as intended but this would require a lot of maintenance and manual changes everytime a package is updated.  
In my specific usecase I am making config packages where the scripts are contained in the package. 

Feature request is would it be possible to have a WSL compatible returned by the %CONFIG% variable or have another variable added such as %WSLCONFIG% that could be used for the windows specific configuration. 

This would allow shell scripts to be used easily on windows via wsl or natively on unix based systems.

This appears to be a further development of https://github.com/espanso/espanso/issues/380 

It could also be used to add to the function of this issue https://github.com/espanso/espanso/discussions/1174 as the OS specific match could ensure that the correct path is used for the same script avoiding the need to duplicate effort rewriting the script for the other OS.

**Comment by kpym** [comment]
You can use `wslpath` to rewrite `$CONFIG` to the desired `$WSLCONFIG`. You can use `$(wslpath -u $CONFIG)` in place of `$WSLCONFIG` or define a new variable `WSLCONFIG` like this:
```yaml
  - trigger: ":config"
    replace: "{{WSLCONFIG}}"
    vars:
      - name: WSLCONFIG
        type: shell
        params:
          cmd: wslpath -u "$CONFIG"
          shell: wsl
```
Now by typing `:config` you get `/mnt/c/Users/user/AppData/Roaming/espanso`

**Notes:** 
- I don't know why `wslpath -u $CONFIG` (wihout quotes) and `$(wslpath -u "$CONFIG")` (with quotes) are not working properly, so be careful how you use `wslpath`  
- `cmd: WSLCONFIG=$(wslpath -u $CONFIG); echo $WSLCONFIG` is not working. We can't set the variable inside wsl, I don't know why.
