### DISCUSSION TITLE
How can i do this?, ":cdb 3" replace as "cd ../../../"

### DISCUSSION THREAD

**Discussion by sweard** [espanso/espanso#1386] [Q&A] [answered]
the 3 is variable parmater.
anyone can help?
thanks.

**Comment by kpym** [comment, marked as answer]
You can use `regex` to recover the number parameter, and then use a script to produce the output.

```yaml
  - regex: ":cdb (?P<num>\\d+) "
    replace: "cd {{cd}}"
    vars:
      - name: cd
        type: shell
        params:
          cmd: "for i in {1..{{num}}}; do echo -n '../';done"
          shell: wsl
```
Remarks:
1. In this code I use `bash` script under Windows. If you are not under Windows like me, you can remove `shell: wsl`. 
2. You can use any other script language to produce "../../../".
3. I use space after the digits to triger the execution, but you can put any non other symbol.
