### DISCUSSION TITLE
Least privilege principle and include/exclude rules and imports

### DISCUSSION THREAD

**Discussion by Dlakoms** [espanso/espanso#1393] [Feature requests and Ideas]
In order to respect the least privilege principle, and so, while making configurations on which match files should be considered or ignored : Not being able to use /config/ subdirectories nor adding more depth inside of /config/ files tends to clutter the directory and complexify the /config/ and /match/ configurations. 

Example : 
- If I want to configure a browser "filter" for matches
- With a dedicated page title filter for Gmail, Facebook, or else (because context matters to declutter the namespace)
I need to have a file called "firefox", with a file called "Inbox" etc. which could cause UX entropy at some point

Possible solutions : 
- Include sub directories config files in the /config/ directory to be considered on reload
- Add more depth in terms of configurations inside a given /config/ file letting configuration based on filter_exec and title_exec like so : 
```yaml
filter_exec: "firefox.exe"
  filter_title: "Inbox"
    extra_includes:
      - "../match/_gmail.yml"
```
or 
```yaml
filter_title: "Inbox"
  filter_exec: "firefox.exe"
    extra_includes:
      - "../match/gmail/_firefox.yml"
```
Or in a trigger / replace like fashion
- Add match context (/config/mycontext.yml) list attributes to matches instead of importing them from the /config/mycontext.yml

Note : I could make another Feature Request around another idea, but it will lack context without the above : 
- Add a "Search Bar" context / list of config files to the #detect# feature to verify which config applies to the given context.
