### DISCUSSION TITLE
Espanso providing output with colons not working outside of terminal

### DISCUSSION THREAD

**Discussion by ggonmar** [espanso/espanso#1419] [Q&A]
I've put together a replacement script of [Espanso](https://espanso.org/), so a call to an API is done and it returns a url contained on the response to the API.
This is the .yml chunk I've created:
```
  - regex: ":spongebob\\((?P<meme>.*)\\)"
    replace: "{{meme_result}}"
    vars:
      - name: meme_result
        type: shell
        params:
          cmd: "curl -s --request POST 'https://api.imgflip.com/caption_image?template_id=182442076&text0={{meme}}&username=user&password=paswword' | jq -r '.data.url'"
```
The curl command returns something like:
```
{"success":true,"data":{"url":"https:\/\/i.imgflip.com\/6yblu0.jpg","page_url":"https:\/\/imgflip.com\/i\/6yblu0"}}
```
and running it with jq does return a valid url:
```
>> curl -s --request POST 'https://api.imgflip.com/caption_image?template_id=182442076&text0=test&username=user&password=password' | jq -r '.data.url'
<<https://i.imgflip.com/6ybmkf.jpg
```
Not sure where the problem is (jq? bash? espanso?), but if I run the espanso command on a terminal, then the url is returned correctly:
`https://i.imgflip.com/6ybmkf.jpg`

However, if I run it anywhere else (this form, for example), typing :spongebob(sd) then I get the url without the : on it:
`https//i.imgflip.com/6ybxtu.jpg`
Obviously destroying the usage of it.

Why is this happening? How can I solve it?
