### DISCUSSION TITLE
Start script without vars usage

### DISCUSSION THREAD

**Discussion by kpym** [espanso/espanso#1449] [Feature requests and Ideas]
It will be nice if we can associate a trigger to a script without waiting to the output.

For example, currently, as a workaround of #1234, I use the following match in `base.yml`: 
```yaml
  - trigger: "!edit"
    replace: "{{output}}"
    vars:
      - name: output
        type: script
        params:
          args:
            - code
            - '%CONFIG%'
```

It works, but I have to manually delete `!edit` after that.

So my suggestion is to have the possibility to do something like this
```yaml
  - trigger: "!edit"
    script:
      args:
        - code
        - '%CONFIG%'
```
which : 
- starts the script as an independent process,
- returns without waiting for the output, 
- removes the trigger (as if `replace: ""`).
