### DISCUSSION TITLE
Add Sound Effect Upon Text Expansion

### DISCUSSION THREAD

**Discussion by andrewcincotta** [espanso/espanso#1465] [Feature requests and Ideas]
I think this feature would be really neat, especially if there were a config setting to enable, disable, or set the sound effect path.
I personally like aText's expansion sound.

**Comment by royemosby** [comment]
This would be handy, especially with my typo expansions. It would keep me from reaching for the backspace key.

**Comment by pitkling** [comment]
I stumbled upon this and some older issues/discussions (#221 and #1170) while searching for whether this is possible with espanso or not. While it still seems not to be supported per se, the shell/script extensions allow for a workaround that might be good enough for some use cases. You can define a variable like

```yml
- name: playsound
  params:
    cmd: /usr/local/bin/play <path_to_sound_file>
  type: shell
```

and then use it in a trigger via

```yml
- replace: '<otherstuff>{{playsound}}'
  trigger: '!foo'
```

The `play` command above is just an example (it's part of the `sox` package on most Linux distributions) and must be adapted according to your system. If you use another command, you might need to surpress standard output (`play` does not output anything on stdout). ~~Something like `'echo -en "\007"'` should also work as the `cmd` in `playsound` above~~ (not really, only for substitutions within a terminal...).

It adds a small delay and needs to be explicitly set for each trigger, but at least for me it is good enough until a proper solution is available.

**Comment by smeech** [comment]
That's neat - thank you. Very dependent on having a command-line sound player, and which one. I found I can use:
```yml
  - name: playsound
    params:
      cmd: paplay /usr/share/sounds/LinuxMint/stereo/button-pressed.ogg
```
is faster than `ffplay -v 0 -nodisp -autoexit /usr/share/sounds/LinuxMint/stereo/button-pressed.ogg`
As you say, the need to add it to each trigger, and the delay, makes it unusable in regular typing.

**Comment by andrewcincotta** [comment]
Create contributions guys! I was wondering which command-line sound player would provide the fastest output for macOS? I am currently using mpv.

Additionally, I am having trouble implementing the play variable to specific triggers. This is what I have, which does not run:
```yml
# Play click sound
  - name: playsound
    params:
      cmd: /opt/homebrew/bin/mpv "/Users/andrew/Library/Mobile Documents/com~apple~CloudDocs/Programming/Utils/Click.aif"
      type: shell

  - trigger: "!foo "
    replace: "something{{playsound}}"
```
