### DISCUSSION TITLE
Different  'replace' according to time

### DISCUSSION THREAD

**Discussion by RicoLaaa** [espanso/espanso#1466] [Q&A] [answered]
Hi!

Is there a way with the same trigger, to have a different replace according to the time?

For example `:greet` would be replaced by `Good Morning` or `Good day` or `good evening` depending on which time of the day you are typing the trigger.

Thanks for your help!

**Comment by dcvn** [comment, marked as answer]
With the `date +%H` command in bash, you known the hour of the day.
Using that, you could do something like:

```yaml
  - trigger: ":greet"
    replace: "{{output}}"
    propagate_case: true
    vars:
      - name: output 
        type: shell
        params:
          cmd: "case $(date +%H) in 0[6-9] | 1[0-1]) echo \"good morning\";; 1[2-7]) echo \"good day\" ;; 1[8-9] | 2[0-3]) echo \"good evening\";; 0[0-5]) echo \"good night\" ;; esac"
```

**Reply by RicoLaaa** [reply]
Thanks @dcvn ! That works like a charm on macOS but unfortunately returns an error on windows probably need some replacement for bash?

Cheers

**Reply by dcvn** [reply]
With the script extension, you can use the language of your choice, available on your system,  to produce your output.

For example, if you have PHP 8, you could do:
```yaml
  - trigger: ":greet"
    replace: "{{output}}"
    propagate_case: true
    vars:
      - name: output
        type: script
        params:
          args:
            - php 
            - "%CONFIG%/scripts/greet.php"  
```

Then in `greet.php` something like

```php
<?php
$dayQuarter = (int) floor(date('H') / 6);
echo match ($dayQuarter) {
  0 => 'good night',
  1 => 'good morning',
  2 => 'good afternoon',
  3 => 'good evening',
  default => 'scary leap hour!'
};
```

It is just an example. Any language can do this.
