### DISCUSSION TITLE
Loading feature

### DISCUSSION THREAD

**Discussion by kud** [espanso/espanso#1472] [Feature requests and Ideas]
Hey,

I've got a feature request for you.

Imagive you've got something like this:

```
  - trigger: "&weather"
    replace: "{{output}}"
    vars:
      - name: output
        type: shell
        params:
          cmd: "curl 'http://wttr.in/?format=3'"
```

and you type `&weather`.

Sometimes the curl command could a be slow and you don't have any feedback so you don't know that espanso will replace the command.

Is there a way to provide a feedback like a loader? or could we add it into espanso?

Thank you,
