### DISCUSSION TITLE
Match-Triggers / Match-Modifiers?

### DISCUSSION THREAD

**Discussion by nudefireninja** [espanso/espanso#1500] [Q&A] [answered]
Is it possible to trigger another match using the output of a prior match?

For example:

``` yaml
- trigger: "snowman"
  replace: "☃.com"
- trigger: "☃.comidn"
  replace: "xn--n3h.com"
```

So if I trigger the first match and then type "idn" after it, it _should_ erase the `☃.com` and replace it with the new match (or maybe "submatch") `xn--n3h.com` (the IDNA encoded version of the domain name). It does not do this currently because espanso seems to ignore the output of a preceding match for the purpose of triggering a new match.

It seems this is not possible but maybe I'm overlooking some option.

My current workaround would be to have both triggers with a unique suffix (or prefix), for example "snowmanuni" and "snowmanidn".
