### DISCUSSION TITLE
Can I have a piece of text that contains a matching rule, and then paste that text when the rule inside is automatically triggered?

### DISCUSSION THREAD

**Discussion by fakerange** [espanso/espanso#1504] [Q&A]
Can I have a piece of text that contains a matching rule, and when paste that text  the rule inside is automatically triggered?
for exmple, when copy text as follow
```
today is :date
```
when I paste(Ctrl + V) it to some where , it will be change to this:
```
today is 2023.01.17
```

**Comment by smeech** [comment]
Sorry about the late reply - I am trying to mop up and sort the old Issues and Discussions.

I'm afraid Espanso only responds to keyboard character input. A lot of people use expansions that don't rely on trigger characters like “:”, so there would be a real risk of triggering expansions inadvertently if one could do so by pasting.

The solution to your example is to have an expansion that outputs `today is 2023.01.17` in response to a particular trigger. [Nested matches](https://espanso.org/docs/matches/basics/#nested-matches) allow you to use one (the date format) inside another expansion, which generates the `today is ` prefix.

**Comment by kpym** [comment]
If you accept to replace the <kbd>Ctrl+V</kbd> with an espanso trigger you can do this

```yaml
  - trigger: ":pwd"
    replace: "{{output}}"
    vars:
      - name: "clipboard"
        type: "clipboard"
      - name: time
        type: date
        params:
          format: "%H:%M"
      - name: date
        type: date
        params:
          format: "%Y.%m.%d"
      - name: output
        type: shell
        params:
          shell: wsl
          cmd: echo "{{clipboard}}" | sed -e 's/:time/{{time}}/g' -e 's/:date/{{date}}/g'
```

So if you copy `The date is :date and now is :time` and type <kbd>:pwd</kbd> somewhere (for **p**aste **w**ith **d**ate) you will get `The date is 2023.12.17 and now is 10:38`.

Remarks: I'm on windows, so I use `shell:wsl`, but if you're not, you can replace it with `shell:bash` or just remove this line.
