### DISCUSSION TITLE
How to publish a package that includes external scripts?

### DISCUSSION THREAD

**Discussion by reitzig** [espanso/espanso#1558] [Q&A]
I have created a few triggers for myself that use external (Python) scripts.

I can't tell from the documentation how to bring these into package form; where do the scripts go?

**Comment by reitzig** [comment]
I came up with a workaround for [reitzig/espanso-nice-dev-refs](https://github.com/reitzig/espanso-nice-dev-refs): clone the repo, install as external package from _local_ source and symlink the scripts.

Would appreciate an extension to the package format that makes that obsolete. :)

**Reply by reitzig** [reply]
@federico-terzi , since you are back: Any thoughts?

**Comment by reitzig** [comment]
Should scripts become first-class citizens in packages, I would suggest to add a matching variable type. Instead of

```yaml
vars:
  - name: label
    type: shell
    params:
      cmd: "python3 ${CONFIG}/scripts/label_for_url.py ${ESPANSO_CLIPBOARD}"
      trim: true
```

I would prefer to write

```yaml
vars:
  - name: label
    type: script
    params:
      cmd: "./label_for_url.py ${ESPANSO_CLIPBOARD}"
      trim: true
```

since espanso _knows_ where the script is, and can rely on shebangs for choosing the correct interpreter (or delegate that to a shell).

**Comment by smeech** [comment]
Do scripts not work if included alongside the `.yml` and other files in the relevant package directory? Not the recommended location, I know.
A related issue is how to include user-data files, which aren't overwritten or deleted when the package is updated. Currently, these have to be moved manually to the /match directory to preserve them.

**Comment by smeech** [comment]
Ideally, for expansion, scripts should be brief, in which case they _could_ be embedded entirely in the `.yml`, e.g.:
```
  - trigger: :test
    replace: "{{output}}"
    vars:
      - name: output
        type: script
        params:
          args:
            - python3
            - -c
            - |
              fruits = ["apple", "banana", "cherry"]
              for x in fruits:
                print(x)
```
in the same way as one can with shell scripts.
