### DISCUSSION TITLE
Microphone access

### DISCUSSION THREAD

**Discussion by rohitna** [espanso/espanso#1564] [Feature requests and Ideas]
It would be great if Espanso could take microphone inputs. This would enable interesting applications such as talking to chatGPT on the fly.

The main problem right now is that I am unable to get Espanso microphone access via a python script by using a trigger of the following format:

```
  # Sound based query
  - trigger: ";talk"
    replace: "{{output}}"
    vars:
      - name: output
        type: shell
        params:
          cmd: '{{PYTHON_ENV}} {{SCRIPT_PATH}} --record'
```

I have tried tinkering with the TCC database `'/Library/Application Support/com.apple.TCC/TCC.db'` but could not get any recordings via Espanso. The script works well without Espanso and uses [pvrecorder](https://github.com/Picovoice/pvrecorder).
