### DISCUSSION TITLE
Using {{clipboard}} in lists

### DISCUSSION THREAD

**Discussion by dodalovicgran** [espanso/espanso#1604] [Q&A]
Hi, I'm pretty sure I'm doing something stupid:

```yaml
  - trigger: ":li"
    form: |
      [[choices]]
    vars:
      - name: "clipboard"
        type: "clipboard"
    form_fields:
      choices:
        type: list
        values: |
          Hi, {{clipboard}}! Thank you for accepting my connection request.
          Hi, there!
          {{clipboard}}, I haven't heard from you in a while. I hope you are doing well.
```

When invoking this, i get some error printed out....
I'm using 2.1.8

Thank you!
