### DISCUSSION TITLE
Variables in list- or choice-form values

### DISCUSSION THREAD

**Discussion by alexander-seidl** [espanso/espanso#1608] [Feature requests and Ideas]
First of all, I want to say what a wonderful app espanso is. I like to use it.

Now for a proposal that would take the DRY (Don't repeat yourself) idea even further: The possibility to use variables in list- or choice-form values.

Here's an example of what I mean by that:

The match under [1] works. When I type :test_form, a form appears that lets me enter a tfield - text and select an option from a list form.

But what I would really like is a match like in [2].
The YAML text is the same as in [1], except that the list-form values are now variables.

However, the latter does not work and leads to an error [3].

I would have expected the variables `{{very_long_text_A}}` and `{{very_long_text_B}}` to be replaced by the match triggers in the vars.

What do you think about this proposal?

[1]

<details>
<summary>This match works</summary>

### List-Form-Values without variables

```yaml
matches:
 - trigger: ":very_long_text_A"
    replace: "text_A_text_A_text_A_text_A_text_A_text_A_text_A_text_A_text_A"

  - trigger: ":very_long_text_B"
    replace: "text_B_text_B_text_B_text_B_text_B_text_B_text_B_text_B_text_B"

  - trigger: ":test_form"
    replace: |
      tfield:
      {{form1.tfield}}
      
      Placed by match_var:
      {{very_long_text_A}}
      {{very_long_text_B}}
      
      Placed by list_form:
      {{form1.lfield}}
      
    vars:
      - name: "form1"
        type: form
        params:
          layout: |
            tfield:
            [[tfield]]
            
            lfield:
            [[lfield]]
          fields:
            tfield:
              multiline: false
            lfield:
              type: list
              values:
                - very_long_text_A
                - very_long_text_B
      - name: "very_long_text_A"
        type: match
        params:
          trigger: ":very_long_text_A"
      - name: "very_long_text_B"
        type: match
        params:
          trigger: ":very_long_text_B"
```

</details>

[2]

<details>

<summary>This match does not work</summary>

### List-Form-Values with variables

```yaml
matches:
 - trigger: ":very_long_text_A"
    replace: "text_A_text_A_text_A_text_A_text_A_text_A_text_A_text_A_text_A"

  - trigger: ":very_long_text_B"
    replace: "text_B_text_B_text_B_text_B_text_B_text_B_text_B_text_B_text_B"

  - trigger: ":test_form"
    replace: |
      tfield:
      {{form1.tfield}}
      
      Placed by match_var:
      {{very_long_text_A}}
      {{very_long_text_B}}
      
      Placed by list_form:
      {{form1.lfield}}
      
    vars:
      - name: "form1"
        type: form
        params:
          layout: |
            tfield:
            [[tfield]]
            
            lfield:
            [[lfield]]
          fields:
            tfield:
              multiline: false
            lfield:
              type: list
              values:
                - {{very_long_text_A}}
                - {{very_long_text_B}}
      - name: "very_long_text_A"
        type: match
        params:
          trigger: ":very_long_text_A"
      - name: "very_long_text_B"
        type: match
        params:
          trigger: ":very_long_text_B"
```

</details>

[3]

<details>

<summary>Errormessage</summary>

### Error occurs when variables are used in list-form-values

```
[ERROR] failed to load variable: YAMLVariable { name: "form1", var_type: "form", params: Mapping { map: {String("layout"): String("tfield:\n[[tfield]]\n\nlfield:\n[[lfield]]\n"), String("fields"): Mapping(Mapping { map: {String("tfield"): Mapping(Mapping { map: {String("multiline"): Bool(false)} }), String("lfield"): Mapping(Mapping { map: {String("type"): String("list"), String("values"): Sequence([Mapping(Mapping { map: {Mapping(Mapping { map: {String("very_long_text_A"): Null} }): Null} }), Mapping(Mapping { map: {Mapping(Mapping { map: {String("very_long_text_B"): Null} }): Null} })])} })} })} }, inject_vars: None, depends_on: [] }

Caused by:
    invalid key format
```
</details>
