### DISCUSSION TITLE
We can use different triggers to execute one replacement, why dont we have one trigger to execute many replacements?

### DISCUSSION THREAD

**Discussion by rafo** [espanso/espanso#1611] [Feature requests and Ideas]
We can use different triggers to execute one replacement like:

```
  - triggers: ["+a", "+b", "+c"]
    replace: "abc"
```

It would be beneficial to use _one_ trigger to execute different replacements (or to be precise, show the espanso _choose replacement window_). This way we can write our rules without redundant triggers like:

```
matches:
  - trigger: "+str"
    replace: "Homestr."
  - trigger: "+str"
    replace: "Homestr. 48"
  - trigger: "+str"
    replace: "Homestreet"
  - trigger: "+str"
    replace: "Homestreet 48"
  - trigger: "+str"
    replace: "Workstreet"
  - trigger: "str"
    replace: "Workstreet 11"
```

And provide cleaner code like:

```
matches:
  - trigger: "+str"
    replace: ["Homestr." ,"Homestr. 48" ,"Homestreet" ,"Homestreet 48" ,"Workstreet" ,"Workstreet 11"]
```

Maybe we should avoid using multiple ```triggers``` to reduce complexity, but that depends on your codebase.
