### DISCUSSION TITLE
Nested Matches Simplification

### DISCUSSION THREAD

**Discussion by FabianoLothor** [espanso/espanso#1635] [Feature requests and Ideas]
Wouldn't be more clean to have the following or similar syntax:

```yml
  - trigger: ":one"
    replace: "nested"

  - trigger: ":nested"
    replace: "This is a {% :one %} match"
```
Against the following?

```yml
  - trigger: ":one"
    replace: "nested"

  - trigger: ":nested"
    replace: "This is a {{output}} match"
    vars:
      - name: output
        type: match
        params:
          trigger: ":one"
```

**Comment by dstark** [comment]
> Wouldn't be more clean to have the following or similar syntax:
> 
> ```yaml
>   - trigger: ":one"
>     replace: "nested"
> 
>   - trigger: ":nested"
>     replace: "This is a {% :one %} match"
> ```
> 
> Against the following?
> 
> ```yaml
>   - trigger: ":one"
>     replace: "nested"
> 
>   - trigger: ":nested"
>     replace: "This is a {{output}} match"
>     vars:
>       - name: output
>         type: match
>         params:
>           trigger: ":one"
> ```

I've been bumping into this too but have found that it's possible to define the output of a function as a global variable. So, that removes the need to define it as a variable for each function in which it's used.

**Comment by smeech** [comment]
I agree, it's clumsy, but it fits the general  `vars:` syntax, which keeps things simple for the rare occasions in which they're useful. YAML can be verbose, but that makes it readable. The only match of this type I use is for my address, which incudes nested matches for my postcode and telephone numbers, which have triggers of their own, so I can use them separately too.

You _could_ use the flow sequence format for vars, e.g.:
```yml
  - trigger: ":nested"
    replace: "This is a {{output}} match"
    vars: [{name: output, type: match, params: {trigger: ':one'}}]
```
but that's less readable.    

`global_vars:` and `anchors:` are generally much more flexible, otherwise, IMHO.
