### DISCUSSION TITLE
Grouping Triggers / Triggers Prefix

### DISCUSSION THREAD

**Discussion by FabianoLothor** [espanso/espanso#1639] [Feature requests and Ideas]
Let's imagine the following:

```yml
matches:

    - triggers:
        - ";pp"
        - ";personal phone"
      replace: "+99 (999) 999 999 999"

    - triggers:
        - ";pa"
        - ";personal address"
      replace: "Foo Bar Baz"

    - triggers:
        - ";wp"
        - ";work phone"
      replace: "+11 (111) 111 111 111"

    - triggers:
        - ";wa"
        - ";work address"
      replace: "Baz Bar Foo"

```

I'd like to be able to create prefix for certain groups (like work groups, app groups, game groups, .c)

```yml
matches:

    - group:
      triggers:
        - ";p"
        - ";personal "

        - triggers:
            - "p"
            - "phone"
          replace: "+99 (999) 999 999 999"

        - triggers:
            - "a"
            - "address"
          replace: "Foo Bar Baz"


    - group:
      triggers:
        - ";w"
        - ";work "

        - triggers:
            - "p"
            - "phone"
          replace: "+11 (111) 111 111 111"

        - triggers:
            - "a"
            - "address"
          replace: "Baz Bar Foo"
```

Or simply:

```yml
prefixes:

    - personal:
        - ";p"
        - ";personal "
    - work:
        - ";w"
        - ";work "

matches:

    - triggers:
        - "p"
        - "phone"
      replace: "+99 (999) 999 999 999"
      prefix: personal

    - triggers:
        - "p"
        - "phone"
      replace: "+11 (111) 111 111 111"
      prefix: work
```
