### DISCUSSION TITLE
replace with files / content that is not text

### DISCUSSION THREAD

**Discussion by schrmh** [espanso/espanso#1640] [Feature requests and Ideas]
(There is #1323 but that is about text from files. My case is about non-text content and files of any type)

I tried a bunch of ways but it looks like that replace can only paste out text in a construct like that:

```
  - trigger: ":file"
    replace: "{{output}}"
    vars:
      - name: output
        type: shell
        params:
          cmd: ""
```
          
For example, I tried to write to /dev/stdout and to use xclip to paste files. Both did not work.
Imo the file picker example that is in the documentation is also a bit misleading since it is only pasting file paths instead of the files.
