### DISCUSSION TITLE
Align forms thru tables

### DISCUSSION THREAD

**Discussion by BasM12345** [espanso/espanso#1667] [Feature requests and Ideas]
Is it possible to make the output for the forms more aligned. Like a table or so?

**Comment by smeech** [comment]
If you separate the form in `vars:` from the output in `replace:` you can format the latter however you like (probably `\t` tabs), e.g.:
```
  - trigger: ":greet"
    replace: "{{form1.name}}\t\t{{form1.surname}}"
    vars:
      - name: "form1"
        type: form
        params:
          layout: |
            [[name]] [[surname]]
```
See https://espanso.org/docs/matches/forms/#using-forms-with-script-and-shell-extensions.
