### DISCUSSION TITLE
Offer a way for capitalizing the first letter of a sentence

### DISCUSSION THREAD

**Discussion by Glyphack** [espanso/espanso#1678] [Feature requests and Ideas]
I was looking for a way to capitalize the first letter of a sentence. I was hoping to make it work by using [regex triggers](https://espanso.org/docs/matches/regex-triggers/), but I could not.

The solution I tried to use was to use a regex that matches the characters after two situations:
- ". "
- line break or first letter of word(^)

The first part of my problem was that I cannot use '^' for regex matches. A match like:

```
  - trigger: "^a"
    replace: "A"
```

I guess this problem might be hard, because the espanso has to know if this is beginning of the sentence.

Other problem I have is to have a capitalize rule in regex. Like sed's `\U`([example](https://unix.stackexchange.com/questions/260762/convert-all-text-in-a-file-to-uppercase-using-sed-and-interested-to-use-range-op))

for the second problem I used a [workaround](https://github.com/Glyphack/dotfiles/blob/a3a70b7e28be35716e796a2cced0c690f9919e14/espanso/match/captials.yml#L8).

**Comment by smeech** [comment]
This mostly works, but relies on seeing a period, question or exclamation mark at the end of the previous sentence:
```yaml
  - regex: (?P<before>\w\[.?!])\s(?P<firstchar>[a-z])(?P<therest>\w*\W)
    replace: "{{before}} {{capital}}{{therest}}"
    vars:
      - name: capital
        type: shell
        params:
          cmd: "echo \"${ESPANSO_FIRSTCHAR^}\""
```
Edit: last two characters of regex changed from `\s` to `\W`.

**Comment by Glyphack** [comment]
Hi @smeech I tried it but could not get it to work. I tried the following:

```
something. next
           ^
```

at this character I expected it to capitalize but did not.

**Reply by smeech** [reply]
It does look for a space at the end of the following word, although removing the final “\s” in the Regex may enable it to work without.

Can you try it in a different editor to see if it works there, and try `backend: Clipboard` in your `default.yml`? It works here, but I tend to find `backend: Clipboard` more reliable, so it features in several of my app-specific config files.

The `echo \"${ESPANSO_FIRSTCHAR^}\` method refers to Linux bash shell. What is your OS and shell?

**Reply by smeech** [reply]
Alternatively, remove `(?P<therest>\w*\W)` from the regex, and `{{therest}}` from the expansion, so that it triggers at the beginning letter of the following word, without waiting for a complete word. I.e.:
```yml
  - regex: (?P<before>\w[.?!])\s(?P<firstchar>[a-z])
    replace: "{{before}} {{capital}}"
    vars:
      - name: capital
        type: shell
        params:
          cmd: "echo \"${ESPANSO_FIRSTCHAR^}\""
```
