### DISCUSSION TITLE
add ability to do `shift+enter` instead of | or \n

### DISCUSSION THREAD

**Discussion by jpetot** [espanso/espanso#1682] [Feature requests and Ideas]
It whould be nice if we could do shift+enter additionally to \n and |. 
motivation: In some application (such as slack), enter is sending a message where as shift+enter is go to the next line.

**Comment by bartdorlandt** [comment]
This seems to work. 

```
  - trigger: ":anm"
    replace: "Could you approve and merge this? Thanks.\n{{clipboard}}"
    force_clipboard: true
    vars:
      - name: "clipboard"
        type: "clipboard"
```
