### DISCUSSION TITLE
Why isn't regex from the documentatinon not working?

### DISCUSSION THREAD

**Discussion by MoltenMonster** [espanso/espanso#1703] [Q&A] [answered]
I'm trying to get a regex replace working in Obsidian, but while a non regex rule works:

```
filter_exec: "/Applications/Obsidian.app"

matches:
  - trigger: ":espanso2"
    replace: "Hi there!2"
```

But this regex rule I got from here: https://espanso.org/docs/matches/regex-triggers/, doesn't work.

```
filter_exec: "/Applications/Obsidian.app"

matches:
  - regex: ":greet\\((?P<person>.*)\\)"
    replace: "Hi {{person}}!"
```
