### DISCUSSION TITLE
Add support for nested match with images

### DISCUSSION THREAD

**Discussion by OahMada** [espanso/espanso#1707] [Feature requests and Ideas]
Currently, the snippet below would result in an error:

[Espanso]: An error occurred during rendering, please examine the logs for more information.

Log:
03:04:05 [worker(13111)] [ERROR] unable to find sub-match: image
03:04:05 [worker(13111)] [ERROR] error during rendering: rendering error

Caused by:
    missing sub match

```
 - trigger: ':text'
    replace: |
      some random text
      {{image}}
    vars:
      - name: image
        type: match
        params:
          trigger: ':image'
```
