### DISCUSSION TITLE
Injecting variables into nested matches

### DISCUSSION THREAD

**Discussion by FynnFreyer** [espanso/espanso#1753] [Q&A] [answered]
Does anyone know a way to inject variables into nested matches? It would be nice to overwrite default fields in sub matches, because that way you could modularize and reuse more.

Here's an example of what I mean:

```yaml
matches:
  - trigger: ':default_fraction'
    replace: '\frac{{{numerator}}}{{{denominator}}}'
    label: 'A LaTeX fraction that is empty by default'
    vars:
      - name: numerator
        type: echo
        params:
          echo: $|$
      - name: denominator
        type: echo
        params:
          echo: ''

  - trigger: ':specific_fraction'
    replace: '\left( {{fraction}} \right)'
    label: 'A specific LaTeX fraction that re-uses the general fraction'
    vars:
      - name: numerator
        type: echo
        params:
          echo: specific numerator
      - name: denominator
        type: echo
        params:
          echo: specific denominator
      - name: fraction
        type: match
        depends_on: ['numerator', 'denominator']
        params:
          trigger: ':default_fraction'
          # the following parameters should be injected into the :default_fraction vars
          numerator: '{{numerator}}'
          denominator: '{{denominator}}'

```

**Comment by FynnFreyer** [comment]
This snippet doesn't work, it's just to clarify the idea

**Comment by AucaCoyan** [comment]
Hi! Thanks for the question. I'm new to espanso and to the repo too! I read your post and thought that maybe you have to escape the triple `{`.
Also, I don't understand what is the expected result, because I don't use Latex. Can you elaborate a bit more please? 🙏🏼

**Reply by FynnFreyer** [reply]
Hey, thanks for your reply.

Expected output for `:specific_fraction` would be `\left( \frac{specific numerator}{specific denominator} \right)`. What this actually expands to is `\left( \frac{$|$}{} \right)` though (with the cursor being moved to `$|$`)

If I triple brace the specific fraction (`replace: '\left( {{{fraction}}} \right)'`), it comes out as `\left( {\frac{}{}} \right)`, so unfortunately that doesn't help. But thank you for the suggestion

I think I'm going to see if I can do something using the environment and shell variables

**Comment by FynnFreyer** [comment]
I've been playing around with how espanso nested matches work, and it seems that espanso doesn't pass the environment of the caller to the nested match. I've reworked the example so that typing `:tb` now prints out the environment variables, and get's output from a nested match, which in turn dumps its own environment.

```yaml
matches:
  - trigger: ':ta'
    force_clipboard: true
    replace: |
      Inner env:
      {{env}}
    vars:
      - name: env
        type: shell
        params:
          cmd: 'env | grep -i espanso'
      - name: var
        type: shell
        params:
          cmd: 'echo ${ESPANSO_OUTER_VAR:-inner default}'

  - trigger: ':tb'
    force_clipboard: true
    replace: |      
      Outer env:
      {{outer_env}}
      
      {{inner}}
    vars:
      - name: outer_var
        type: shell
        params:
          cmd: echo a
      - name: outer_env
        type: shell
        depends_on: ['outer_var']
        params:
          cmd: env | grep -i espanso
      - name: inner
        type: match
        depends_on: ['outer_var']
        params:
          trigger: ':ta'
          # the following parameters should be injected into the environment
          var: '{{outer_var}}'
          outer_var: '{{outer_var}}'
```

This produces output like the following:

```
Outer env:
ESPANSO_OUTER_VAR=a
CONFIG=/home/fynn/.config/espanso

Inner env:
CONFIG=/home/fynn/.config/espanso
```

I think I could write stuff in some cache file, and get it from there, but that seems really miserable. Anyone got a better idea?

**Reply by AucaCoyan** [reply]
Yeah, that seems unnecessary complicated. Let me tag @federico-terzi , the maintainer 
Sorry for the tag! do you know any that could help?

**Reply by FynnFreyer** [reply]
It's somewhat possible with `espanso match exec -t <trigger> --arg key=val`.

```yaml
matches:
  - trigger: ':ta'
    force_clipboard: true
    replace: '{{var}}'
    vars:
      - name: var
        type: shell
        params:
          cmd: 'echo ${ESPANSO_OUTER_VAR:-inner}'
  - trigger: ':tb'
    force_clipboard: true
    replace: '{{test}}'
    vars:
      - name: test
        type: shell
        params:
          cmd: 'espanso match exec -t :ta --arg outer_var=outer'
```

This has the problem that it executes the match instead of expanding it and printing to stdout. So it deletes some text before and does weird things. All in all it feels super jank.

I think a good solution would be a `--to-stdout` flag for the `exec` subcommand, that just prints the expanded match. I'll open a new post for a feature request, but leave this one open in case someone has a better idea to make this work
