### DISCUSSION TITLE
Adding '#' characters to multiline text?

### DISCUSSION THREAD

**Discussion by egoodwintx** [espanso/espanso#1757] [Q&A] [answered]
Hi all, 

Since the # character is a comment in YAML, how would I include a # character in multiline snippets?  For example, if I had a C language snippet like:
#include <stdio.h>
#include <stdlib.h>

How would I get espanso to process this correctly?

**Comment by smeech** [comment, marked as answer]
I think this works:
```yaml
  - trigger: :std
    replace: |
      #include <stdio.h>
      #include <stdlib.h>
```
or
```yaml
  - trigger: :std
    replace: "#include <stdio.h>\n#include <stdlib.h>"
```
unless I have misunderstood your question?

See https://yaml-multiline.info/.

You may also be interested in the new [Discord channel](https://discord.gg/4QARseMS6k).
