### DISCUSSION TITLE
Document markdown

### DISCUSSION THREAD

**Discussion by quinn-p-mchugh** [espanso/espanso#1806] [Feature requests and Ideas]
I noticed the Espanso documentation doesn't appear to have `markdown:` and `html:` options called out in the [docs](https://espanso.org/docs/get-started/). 

This feature is valuable, as it helps ensure that templates for email correspondence or WYSIWYG editors, such as Confluence, are properly formatted.

**Examples:** 

```yaml
  - trigger: ":formatashtml"
    html: |
      <h1>This will be formatted as h1</h1>
```

```yaml
  - trigger: ":formatasmd"
    markdown: |
      # This will be formatted as h1
```

Please see here for more info:
https://github.com/espanso/espanso/issues/553#issuecomment-1877340249
