### DISCUSSION TITLE
Previews for images in search/images as labels

### DISCUSSION THREAD

**Discussion by Gremious** [espanso/espanso#1814] [Feature requests and Ideas]
I want to use espanso as a sticker tool for windows, so I can add a pack of images and a config, and now I can send them to friends on discord - but it's pretty hard without previews.

I would be very nice to be able to do something like e.g. :

```yaml
  - trigger: ":mouse_cheese"
    image_path: "C:/Users/Username/Downloads/mouse_cheese.png"
    label: <image path here, or the image from the above if ommited (?)>
```

and get at least something like:

![image](https://github.com/espanso/espanso/assets/21365711/37970e77-2433-4893-932d-8742d88f6705)

If there exists a spearate image-focused app that I can use on Windows I'm happy to hear recomendations, but I have not had much luck finding one.
