### DISCUSSION TITLE
Support interations with selected text

### DISCUSSION THREAD

**Discussion by at-ng** [espanso/espanso#1885] [Feature requests and Ideas]
It would be nice it there was some way of interacting with selected text similar to the [clipboard extension](https://espanso.org/docs/matches/extensions/#clipboard-extension). Maybe with an option to also replace the text or not. For now this would probably require you to trigger the "match" using the search. But if/when keybindings are added (#1188 #1259 #1511) this would be great together with that.

With some simple scripts this could be used for operations such as

- Change to upper/lower/initial case
- Add a comment block (coding)
- Search and replace
- Format text
- Count words

For now the workaround is to cut the text and paste it in a form then I you can access it with the variable (or directly from the clipboard). The disadvantage of course being that your clipboard gets replaced and you need to push a few extra buttons.

**Comment by smeech** [comment]
Those are some interesting ideas. Would you be able to give some more detail? Much of what you suggest can be achieved with the clipboard extension and some brief Scripts or Shell commands (which can be included in the YAML to avoid calling external files), I think, but I may have misunderstood.
```yml
  - trigger: "\x05" # <ctrl-e>
    replace: "{{output}}"
    vars:
      - name: text
        type: clipboard
      - name: output
        type: shell
        params:
          cmd: echo {{text}} | tr '[:upper:]' '[:lower:]'
          shell: bash
```
or
```yml
          cmd: echo '{{text}}'.ToLower()
          shell: pwsh
```
It is a three-step process, however (select text, \<ctrl-c>, \<ctrl-e>).

**Reply by at-ng** [reply]
Yes, as I mentioned in the last line the workaround for this is simply CTRL+X and then CTRL+V in a form (or as you say directly using clipboard). So this is mostly to save on those extra keypresses and having to use a form. If keyboard shortcuts get implemented if would also save the step of having to crop the text before typing a trigger which would make to workflow nice (e.g. select text, CTL+U, text is now upper case).

**Reply by smeech** [reply]
That would be neater. For now one would have to add an `xdotool` or similar command, to invoke \<ctrl-c> as a simulated keypress.
I'm afraid extensions to other keyboard combinations isn't likely to occur soon, despite many requests for it, and many \<ctrl-key> combinations will conflict with the programs in which one would wish to use them.

**Reply by at-ng** [reply]
Ah, yes that is an workaround I should have considered since I [posted about something along those lines yesterday.](https://github.com/espanso/espanso/discussions/1201#discussioncomment-8666987) Collisions are definitely likely so CTRL+SHIFT+U or something might be preferable in the future if full keybinding support gets added.

**Reply by smeech** [reply]
I saw that. The workarounds do get increasingly tortuous!
On Linux, I would envisage detecting a wider range of key combinations with `xbindkeys` to trigger a script, which outputs required text, or triggers an `xdotool` command which can, in turn, trigger an Espanso expansion. By then I've almost cut Espanso out, however!

**Reply by at-ng** [reply]
If it helps anyone this is the workaround I arrived at, it uses a single shared keybinding to avoid collisions (the least likely one CTRL+_). Then it calls a script that calls the other scripts depending on a choice of action.

```
  - trigger: "\x1F"
    label: "Modify selected text CTRL+_"
    replace: "{{output}}"
    vars:
      - name: useless_output
        type: shell
        params:
           shell: powershell
           cmd: (New-Object -ComObject wscript.shell).SendKeys('^c'); Start-Sleep -Seconds 1.0;
      - name: "clipb"
        type: "clipboard"
      - name: script_choice
        type: choice
        params:
          values:
            - label: "Uppercase"
              id: "caseHelper.js UPPER"
            - label: "Lowercase"
              id: "caseHelper.js LOWER"
            - label: "Initcase"
              id: "caseHelper.js INITCAP"
            - label: "Format JSON"
              id: "formatJSON.js"
            - label: "Format HTML"
              id: "formatHTML.js"
            - label: "Solve equation"
              id: "equationSolver.js"
            - label: "Word count"
              id: "wordCount.js YES"
      - name: output
        type: script
        params:
          args:
            - "{{node_exe_path}}"
            - "%CONFIG%/scripts/scriptLaunchHelper.js"
            - "{{script_choice}}"
            - '{{clipb}}'
```
The delay after CTRL+C was necessary to avoid an error accessing the clipboard.

Seems to work fine but you have to make a choice rather than having a keybinding for a specific action.

**Reply by smeech** [reply]
That's neat. Now you just need to share your script!

**Reply by at-ng** [reply]
They are all fairly simple, the launcher is just this node.js script
```
const inpParam = process.argv[2];
const inpParamSplit = inpParam.split(' '); // Allow extra parameters in the choice for when one script has multiple features

const scriptName = inpParamSplit[0];
let inpExtraParams = process.argv.slice(3);
if(inpParamSplit[1]) inpExtraParams = inpParamSplit.slice(1).concat(inpExtraParams);

const childProcess = require('child_process');

let ps = childProcess.fork(__dirname + '/' + scriptName, inpExtraParams);

ps.on('exit', function (code) {
	process.exit(code)
});
```
And for example the caseHelper script looks like this
```
let inpOperation = process.argv[2];
let inpData = process.argv[3];
try {
	let output = inpData;
	switch (inpOperation) {
		case 'UPPER' :
			output = output.toUpperCase();
			break;
		case 'LOWER' :
			output = output.toLowerCase();
			break;
		case 'INITCAP' :
			output = output.toLowerCase().replace(/(?:^|\s)[a-z]/g, function (m) {
				return m.toUpperCase();
			});
			break;
	}
	console.log(output);
} catch (e) {
	console.log(`Failed to ${inpOperation}\n\Error:\n\n${e.message}`)
}
```

**Comment by smeech** [comment]
You've inspired me to produce my own version, with portions unashamedly copied from yours:
```yml
  - trigger: "\x1F" # Select text and hit <CTRL+_>
    label: "Modify selected text CTRL+_"
    replace: "{{output}}"
    vars:
      - name: null
        type: shell
        params:
           shell: bash
           cmd: xdotool key --clearmodifiers ctrl+c
      - name: clipb
        type: clipboard
      - name: script_choice
        type: choice
        params:
          values:
            - label: Uppercase
              id: upper
            - label: Lowercase
              id: lower
            - label: Initcase
              id: initcap
            - label: Evaluate equation
              id: math
            - label: Word count
              id: wordcount
      - name: output
        type: shell
        params:
          shell: bash
          cmd: |
            case "{{script_choice}}" in
              upper)
                echo "{{clipb}}" | tr '[:lower:]' '[:upper:]';;
              lower)
                echo "{{clipb}}" | tr '[:upper:]' '[:lower:]';;
              initcap)
                awk '{for(i=1;i<=NF;i++) $i=toupper(substr($i,1,1)) tolower(substr($i,2))}1' <<< "{{clipb}}";;
              wordcount)
                echo "{{clipb}}" | wc -w;;
              math)
                awk "BEGIN {print {{clipb}}}";;
            esac
```
Thank you!
