### DISCUSSION TITLE
Extension for writing files (and allowing more data sent to scripts)

### DISCUSSION THREAD

**Discussion by at-ng** [espanso/espanso#1886] [Feature requests and Ideas]
I think an extension that is able to write files would be useful. Maybe you want to add something to a list in a different file than the one you are working on, or maybe you want to generate a file using a Espanso form. Or maybe you want to create a new file with your clipboard content. I imagine there are many ways this could be useful.

This would also help bypass the limitations of how much data you can send to a script. An Espanso form can accept a lot of data but when you try to send it to a script I think you are limited by the operating system (windows) to around 32k chars. If instead you could output the data to a file then you could just send its path instead.

Example yml:
```
  - trigger: ":outfile"
    replace: "{{tmpfile}}" # Would just contain the path (if the file was created) more useful for sending to a script
    vars:
      - name: tmpfile
        type: outfile # infile could be useful as well, for example for loading text from a directory (but also possible with scripts)
        params:
          data: "text:\n{{data_variable}}"
          path: "%tmp%/tmpfile.txt"
          mode: append # append / replace / no-overwrite
```

Personally I use forms for now (#1885) to interact with large chunks of text rather than just the trigger itself but it's not uncommon for me to want to do this with larger amounts of text than what is currently possible. Use cases are things like adjusting case, formatting, sorting etc.
