### DISCUSSION TITLE
Add text_path analog to image_path

### DISCUSSION THREAD

**Discussion by bomhard** [espanso/espanso#1908] [Feature requests and Ideas]
Adding longer texts to base.yml may make it hard to read and huge. For that a text_pat function would be really nice. Could work like that:

`    - trigger: ":MyLongText"`
`      text_path: |`
`                 "/path/to/MyLongText"`
</code>

**Comment by joh6nn** [comment]
Probably not a bad idea since we already have image_path and text_path is the obvious counterpart. That said, Espanso supports an unlimited number of yaml files in the configuration directory, so you can move long texts to their own file. You can also use `shell` to output arbitrary text files as the replacement

**Reply by smeech** [reply]
I agree with your latter points. Image injection requires special handling. That having been said, `image_path:` is very limited compared with the `html:` and `markdown:` methods of injecting images, that I'm not sure that we really need it except for compatibility.

Text in much more straightforward, and I've successfully tested simple block scalar and `cmd: cat something.txt` `replace:`s of many thousands of characters.

There's an argument for an OS-independant method (rather than `type` in Windows and `cat` or `echo` or `printf` in Linux & macOS), however, I suppose, but including it in the YAML (in a _match_ directory :smile: ) is simplest.

**Reply by smeech** [reply]
```yml
  - trigger: :test
    replace: "{{output}}"
    vars:
      - name: output
        type: script
        params:
          args:
            - python
            - -c
            - print(open("path/file.txt", "r").read())
```
is pretty OS-independent.
