### DISCUSSION TITLE
Add option to remove trigger word before script runs

### DISCUSSION THREAD

**Discussion by bekoeppel** [espanso/espanso#1931] [Feature requests and Ideas]
I have some scripts that use `xdotool` to send keystrokes. However, once the script has completed, Espanso tries to backspace the trigger word, interfering with my keystrokes.

One solution could be to have an option for a match to remove the trigger _before_ running the script. So:

  * User types `:trg`
  * Espanso does `<Backspace><Backspace><Backspace><Backspace>`
  * Espanso runs the script

**Comment by smeech** [comment]
I agree it would be handy, although it's not too difficult to get around this particular use-case by adding repeated `BackSpace` parameters, matching the length of the trigger, to the `xdotool` command, and dummy characters at the end for Espanso to remove in turn. I recently wrote the following for someone:
```yml
  - trigger: :kp
    replace: "{{output}}"
    vars:
      - name: output
        type: shell
        params:
          cmd: |
            xdotool key BackSpace BackSpace BackSpace type /h1
            sleep 1.5
            xdotool key Return type "HEADER WORDS HERE***"
```
I think there are some environment variables, including one containing the trigger phrase, in the development pipeline, which would make it possible to do this programmatically. This would get around not knowing the length of `regex:` triggers in advance.

See also #1828 & #1858
