### DISCUSSION TITLE
How to pass an inline argument to script?

### DISCUSSION THREAD

**Discussion by gluiz1** [espanso/espanso#2035] [Q&A] [answered]
I am trying to pass an inline argument to a script, but so far without success. 

My goal is to type:

`:test/<ref>/` an pass `<ref>` as an argument to a script. My attempts so far:

```
matches:
  - regex: ":test/<ref>/"
    replace: "{{result}}"
    vars:
      - name: result
        type: script
        params:
        args:
          - python3
          - "path/to/file"
          - "$ESPANSO_REF"
```

But it did not work. How is the standard way to pass some argument to the script through regex?

**Comment by smeech** [comment]
You'll need to use a [named capturing group](https://espanso.org/docs/matches/regex-triggers/#arguments).

You can then pass the variable in the script parameters as, e.g. `- "{{ref}}"`, or picked up within the script `ESPANSO_REF` without needing to be passed.

I think your `args:` and subsequent lines probably need to be indented with respect to `params:`

If you _don't_ put inverted commas around the regex, it may be easier to test in, e.g. https://regex101.com/

I'll be back later when I have more time.

**Comment by smeech** [comment, marked as answer]
```yml
  - regex: :test/(?P<ref>.*)/
    replace: "{{result}}"
    vars:
      - name: result
        type: script
        params:
          args:
            - python
            - "%CONFIG%/scripts/test.py"
            - "{{ref}}"
```
test.py in `espanso/scripts/`:
```py
#!/usr/bin/env python3
import os, sys

# Retrieve the command-line argument
cli_variable = sys.argv[1]

# Retrieve the environment variable
espanso_ref = os.getenv("ESPANSO_REF")

# Print the variables
print(f"CLI Variable: {cli_variable}")
print(f"ESPANSO_REF: {espanso_ref}")
```
Triggered by ":test/something/".

For a short script like this, I would usually put it [inline](https://espanso.org/docs/matches/extensions/#inline-scripts) to avoid worrying about the location and to be able to use `{{ref}}` directly in the script, without "retrieving" it.
