### DISCUSSION TITLE
Export KUBECONFIG with a value coming from list

### DISCUSSION THREAD

**Discussion by dodalovicgran** [espanso/espanso#2157] [Q&A]
Hi, I'd like to have something like this:

https://espanso.org/docs/matches/forms/#list-box

And when I choose a value, it should run `export KUBECONFIG=$value` in my current shell.

So:

* I'm in the shell
* I invoke something
* I choose a value from the list
* it exports the var with that value 

Would this be possible?

Thank you

**Comment by smeech** [comment]
Something like this?

```yml
  - trigger: :kcfg
    form: "export KUBECONFIG=[[item]]\n"
    form_fields:
      item:
        type: choice
        values:
          - first
          - second
          - third
        default: first
```        
Change the values (`first`, `second`, `third`) and the default one, and the trigger to suit.
