### DISCUSSION TITLE
Can espanso cache user input until fully expanded and re-insert typed text?

### DISCUSSION THREAD

**Discussion by mainrs** [espanso/espanso#2293] [Q&A]
I am running Linux, using GNOME on Wayland.

Text expansion works, but I noticed that I cannot continue to type while the text is expanding or else the expanded content contains the characters that I was typing in between. It looks to be like espanso emulates keystrokes.

Is it somehow possible to have the text that I am typing be "cached" and re-inserted after the expansion? I did not change the injection methods, so whatever the default is is what I use.

**Comment by smeech** [comment]
You might find using the `clipboard` backend cooperates better, and may be useful in those environments where you're having this problem.

**Reply by mainrs** [reply]
I already have tried that mode:

```console
$ cat ~/.config/espanso/config/default.yml 
force_mode: clipboard
```

In my case I use the German umlaut extension https://hub.espanso.org/german-accents

```yaml
# German Accents

# Lowercase
matches:
  - trigger: "a\""
    replace: "ä"

  - trigger: "o\""
    replace: "ö"

  - trigger: "u\""
    replace: "ü"

  - trigger: "s\""
    replace: "ß"

# Uppercase

  - trigger: "A\""
    replace: "Ä"

  - trigger: "O\""
    replace: "Ö"

  - trigger: "U\""
    replace: "Ü"
```
