### ISSUE TITLE
Dashes in variable name for date expansions not working

### ISSUE THREAD

**Issue by macintacos** [espanso/espanso#1071]
The following trigger does not seem to work (running `espanso 2.1.5-beta`):

```yaml
matches:
  - trigger: "xds"
    replace: "{{iso8601-date}}"
    vars:
      - name: iso8601-date
        type: date
        params:
          format: "%Y-%m-%d"
```

It just prints out `{{iso8601-date}}`. The following does work:

```yaml
matches:
  - trigger: "xds"
    replace: "{{iso8601date}}"
    vars:
      - name: iso8601date
        type: date
        params:
          format: "%Y-%m-%d"
```

I was reviewing [the Variables documentation](https://espanso.org/docs/matches/variables/) to see if this was called out there as a limitation, but couldn't find anything. Is this a bug, or is this legitimately not supported? I did notice that no examples in the documentation use dashes in the variable names, so it almost feels like the latter, but since it's not explicitly called out I wanted to make sure.
