### ISSUE TITLE
"%Z" does not convert to local time zone name with Date Extension

### ISSUE THREAD

**Issue by macintacos** [espanso/espanso#1072]
**Describe the bug**

Take the following trigger:

```yaml
global_vars:
  - name: todaysDate
    type: date
    params:
      format: "%B %e, %Y"

matches:
  - trigger: "xdut"
    replace: "{{todaysDate}} [{{24HourTime}}]"
    vars:
      - name: "24HourTime"
        type: date
        params:
          format: "%T %Z"
```

According to [the documentation](https://espanso.org/docs/matches/extensions/#:~:text=Local%20time%20zone%20name), I would expect that using the `%Z` specifier would print out the local time zone name:

<img width="649" alt="CleanShot 2022-04-15 at 13 20 07@2x" src="https://user-images.githubusercontent.com/8128941/163601132-860f40a2-a8ee-4794-b1ee-426ca2249dc2.png">

But it doesn't. I get the same thing as the `%z`, which is the offset from the local time to UTC. Expanding the above right now, I get: `April 15, 2022 [13:22:01 -04:00]`

**To Reproduce**

1. Create a trigger with the above
2. Expand the trigger (in this case `xdut`) and observe

**Expected behavior**

The name of the local time zone would be printed out with the time, instead of the offset..

**Setup information**

- OS: macOS 12.3.1
- Version: 2.1.5-beta
