### ISSUE TITLE
Allow type casting in shell commands

### ISSUE THREAD

**Issue by lionawurscht** [espanso/espanso#1076]
**Is your feature request related to a problem? Please describe.**
For my work I often need to calculate dates in the future. I thought I'd try using Espanso to make this task easier. Therefore, I created a regex match to find the date xx weeks from today like so:

```
  - regex: "#in(?P<weeks>\\d+)w"
    replace: "{{date}}/{{weeks_offset}}"
    vars:
      - name: weeks_offset
        type: shell
        params:
          cmd:  "{{weeks}} * 7 * 24 * 60 * 60"
      - name: date
        type: date
        params:
          format: "%x"
          offset: "+{{weeks_offset}}"
```

Unfortunately, I discovered, that the offset param of the date extension doesn't accept strings as it's value (I tried `offset: "+1814400"`).

**Describe the solution you'd like**
I see two solutions: either allow strings as values for offset, or allow type casting in the shell extesion. e.g. like:

```
  - regex: "#in(?P<weeks>\\d+)w"
    replace: "{{date}}/{{weeks_offset}}"
    vars:
      - name: weeks_offset
        type: shell
        params:
          cmd:  "{{weeks}} * 7 * 24 * 60 * 60"
          cast: i32
      - name: date
        type: date
        params:
          format: "%x"
          offset: "+{{weeks_offset}}"
```
Personally, I feel like type casting would be the more flexible approach.

P.S. I only added "{{weeks_offset}}" in the replace value for debugging reasons, actually I'm just looking to create the calculated date.
