### ISSUE TITLE
Form choice box selects a value even if the default is `(empty)`

### ISSUE THREAD

**Issue by revolter** [espanso/espanso#1293]
**Describe the bug**

If you create a simple form with a choice box, the first value gets selected by default, even if you don't set the `default` property.

**To Reproduce**
1. Add this to your config

   ```yaml
   matches:
     - trigger: ":form"
       form: |
         [[choices]]
       form_fields:
         choices:
           type: choice
           values:
             - First choice
             - Second choice
   ```

2. Type `:form`

**Expected behavior**

No value should have been selected by default, because [the documentation](https://espanso.org/docs/matches/forms/#choice-box) states that the default value of the `default` property is `(empty)`, not the first value.

**Screenshots**

<img width="288" alt="image" src="https://user-images.githubusercontent.com/5748627/178665065-91b5e526-1370-49a3-958a-b5616cc36317.png">

**Logs**
If possible, run `espanso log` in a terminal after the bug has occurred, then post the output here so that we can better diagnose the problem

**Setup information**
- OS: macOS 12.4 (21F79)
- Version: espanso 2.1.6-beta
