### ISSUE TITLE
"circular dependency" error when using variable injection for form field defaults

### ISSUE THREAD

**Issue by loilo** [espanso/espanso#1338]
**Describe the bug**
When configuring variable injection for form field default values, a confusing "circular dependency" error is reported.

**To Reproduce**
1. Create the following match:

   ```yml
   - trigger: ":hello"
     replace: '{{greet_form}}'
     vars:
       - name: greet_form
         type: form
         params:
           layout: |
             Hey [[name]]!
           fields:
             name:
               default: '{{default_name}}'
       - name: default_name
         type: shell
         params:
           cmd: "echo 'John Doe'"
   ```

2. Trigger the match by typing `:hello`.

**Expected behavior**
A form for entering a name is shown, the pre-filled value of the name field being "John Doe".

**Screenshots**

<img width="370" alt="The error notification, stating: An error occurred during rendering, please examine the logs for more information." src="https://user-images.githubusercontent.com/1922624/184722528-c7ae2391-8f54-4d8f-ad7d-896e2f4a9030.png">

**Logs**

```
23:34:41 [worker(43419)] [ERROR] error during rendering: rendering error

Caused by:
    circular dependency: `greet_form` -> `default_name`
```

**Setup information**
- OS: macOS 12.3.1
- Version: 2.1.6-beta
