### ISSUE TITLE
Rich text support in a form trigger

### ISSUE THREAD

**Issue by mmikhan** [espanso/espanso#1364]
I am struggling to enable rich text support (Markdown or HTML) in a form-type trigger. I couldn't find such an example and couldn't figure it out myself. I am sharing the following example from the documentation that only offers the form trigger support.

```yml
- trigger: ":form"
    replace: "Hey {{form1.name}}, how are you? Do you like {{form1.fruit}}?"
    vars:
      - name: "form1"
        type: form
        params:
          layout: "Name: [[name]] \nFruit: [[fruit]]"
          fields:
            name:
              multiline: true
            fruit:
              type: list # or `choice`
              values:
                - Apples
                - Bananas
                - Oranges
                - Peaches
```
If I want to add a text paragraph that needs certain words bold, italic, and even a hyperlink, how do I add that, or where do I add that? Appreciate your assistance!
