### ISSUE TITLE
Incorrect and slow replacement in some web forms

### ISSUE THREAD

**Issue by il2020** [espanso/espanso#1366]
I have the trigger:

```yml
  - trigger: ":-"
    replace: "—"
```

And in some textareas it doesn't work as I expect. See the gif:
![Peek 2022-09-03 06-32](https://user-images.githubusercontent.com/77854832/188254314-93782ff5-7c7b-424d-8d56-108f8557bbef.gif)

What can be wrong?

My config:
```yml
# You can refer to the official documentation:
# https://espanso.org/docs/
backspace_limit: 1
enable_passive: true
toggle_key: LEFT_ALT
passive_key: SHIFT
undo_backspace: false
#backend: Inject

# Matches are the substitution rules, when you type the "trigger" string
# it gets replaced by the "replace" string.
matches:
  # Simple text replacement
  - trigger: ":espanso"
    replace: "Hi there!"

  # Dates
  - trigger: ":date"
    replace: "{{mydate}}"
    vars:
      - name: mydate
        type: date
        params:
          format: "%m/%d/%Y"

  # Shell commands
  - trigger: ":shell"
    replace: "{{output}}"
    vars:
      - name: output
        type: shell
        params:
          cmd: "echo Hello from your shell"

  - trigger: ":-"
    replace: "—"

  - trigger: ":code"
    replace: "<code>{{clipboard}}</code>"
    vars:
      - name: "clipboard"
        type: "clipboard"
```

```sh
$ espanso -V
espanso 2.1.6-beta
```
