### ISSUE TITLE
UTF8 Triggers (German Umlauts) on MacOS not working

### ISSUE THREAD

**Issue by dlohm** [espanso/espanso#1471]
**Describe the bug**
```
matches:
  # Simple text replacement
  - trigger: "ggruß"
    replace: "Herzliche Grüße!"
```
I can't get matches with Umlauts (äöüß) to trigger. I also tried the regex-syntax with the explicit unicode code-point `\\u00DF` at no success. 

**Setup information**
- OS: MacOS 12.6 (Montery)
- Version: espanso 2.1.8
