### ISSUE TITLE
Espanso not finding pip3 installed packages on macOS

### ISSUE THREAD

**Issue by josealobato** [espanso/espanso#1474]
**Describe the bug**

I have a python3 script that uses some pip3 packages on my system (Jinja2, yaml). When I run that script on CLI it works as expected but from espanso I get the error:

```
10:34:34 [worker(91881)] [WARN] script command exited with code: exit status: 1 and error: Traceback (most recent call last):
  File "/Users/jose.lobato/Library/Application Support/espanso/scripts/kb_test.py", line 3, in <module>
    from jinja2 import Environment, FileSystemLoader
ModuleNotFoundError: No module named 'jinja2'
```

The shell espanso is creating does not see the `pip3` packages.

**To Reproduce**

I have this packages installed with `pip3`:

```
% pip3 list                                                                                                                                                                                                                                                               
Package    Version
---------- -------
Jinja2     3.1.2
```

The script that I use "simplified" is:

```
 import sys                                           
 import os                                            
 from jinja2 import Environment, FileSystemLoader     
 from datetime import date                            
 import yaml                                          
                                                      
 # Here goes the code of the script that I use        
                                                      
 print("Done!")                                       
```

When I run it in CLI I get (Notice it uses 4 parameters):
```
% python3 kb_test.py "..." "..." "..." "..."
Done!
```

The definition on espanso is:

```
  - triggers: [":kbx", ":kbentrx"]                      
    lable: "Create an entry on the knowledge base"      
    replace: "{{filler}}"                               
    vars:                                               
      - name: aform                                     
        type: form                                      
        params:                                         
          layout: |                                     
            Title [[title]]                             
            Link [[link]]                               
            Subject [[choice]]                          
      - name: filler                                    
        type: script                                    
        params:                                         
          args:                                         
            - python3                                   
            - "%CONFIG%/scripts/kb_test.py"             
            - "{{aform.title}}"                         
            - "{{aform.link}}"                          
            - "{{aform.choice}}"                        
            - "%CONFIG%/scripts"                        
 ```

1. With that configuration just run `:kbx`

**Expected behavior**
I was expecting the script to run as in the console.
The script was running properly and receiving all parameters until I used the external package.

**Setup information**
- OS: macOS 12.5 (`Monterrey`)
- Version: espanso 2.1.8
