### ISSUE TITLE
capture multiple line in clipboard

### ISSUE THREAD

**Issue by tiger360** [espanso/espanso#1503]
**Describe the bug**
If I have for example that in the clipboard, I could not capture it to make it uppercase: 
"NOUVEL AN
asiatique"

**To Reproduce**
`  
- trigger: "::cap"
    replace: "{{output}}"
    vars:
      - name: "clipboard"
        type: "clipboard"
      - name: output
        type: shell
        params:
          shell: wsl
          cmd: "echo $ESPANSO_CLIPBOARD | tr -d '\n' | tr '[:upper:]' '[:lower:]'  "
`
**Expected behavior**
I want to remove the line break and replace it with spaces to be able to uppercase all the sentence

**Setup information**
- OS: Windows 10
- Version: espanso 2.1.5-beta

**Comment by kpym** [comment]
This is not a bug, nor is it a problem related to espanso. This is a problem with the use of bash.

1. If you want to capture all lines, you have to enclose the environment variable in quotes, like this :
    ```bash
    echo "$ESPANSO_CLIPBOARD"
    ```
1. If you want to remove line breaks under windows, you have to use :
    ```bash
    tr -d `\n\r`
    ```
1. If you remove the newlines, you can glue the last word of one line and the first word of the next line... do you want that?
1. You do not need to remove the newlines to convert the clipboard to lowercase.

Here is my suggestion:
```yaml
  - trigger: "::cap"
    replace: "{{output}}"
    vars:
      - name: "clipboard"
        type: "clipboard"
      - name: output
        type: shell
        params:
          shell: wsl
          cmd: echo "$ESPANSO_CLIPBOARD" | tr '[:upper:]' '[:lower:]'

```

Feel free to close this topic if it works for you ;)
