### ISSUE TITLE
how to replace it on special editors (gvim, emacs, etc.) more simply than this way?

### ISSUE THREAD

**Issue by dehydrate-man** [espanso/espanso#1516]
### these are my config:
``` yaml
global_vars:
  - name: "buffer_path"
    type: "echo"
    params:
      echo: "/home/user/espanso_buffer.txt"
  - name: "sendtype_emacs"
    type: "echo"
    params:
      echo: "parallel --ungroup --jobs 1 xdotool search --onlyvisible \"emacs\" windowactivate --sync type --clearmodifiers $'{} $(xdotool key Return)'"
```
``` yaml
matches:
  - trigger: ":xdotool-sendtype-emacs"
    replace: "{{output}}"
    vars:
      - name: output
        type: shell
        params:
          cmd: "cat {{buffer_path}} | {{sendtype_emacs}}"
#some examples
  - trigger: ":hg-css-ds"
    replace: "{{output}}"
    vars:
      - name: output
        type: shell
        params:
          cmd: "echo '#+html: <style>details summary { color: #cd00cd; }</style>\n#+html: <style>details .details { color: #ff54ff; }</style>\n' > {{buffer_path}}"
```
### when I add a new entry, thus:
``` yaml
  - trigger: ":shell"
    replace: "{{output}}"
    vars:
      - name: output
        type: shell
        params:
          cmd: "echo 'Hello from your shell' > {{buffer_path}}"
```
If anyone has any good ideas, please let me know.
