### ISSUE TITLE
Not executing in Neovide. Only whitespace is being entered.

### ISSUE THREAD

**Issue by y1feng200156** [espanso/espanso#1551]
**Describe the bug**
When entering `:shell` in [Neovide](https://neovide.dev/), only a blank space is displayed without any output.

**To Reproduce**
1. Open Neovide.
2. Enter insert mode.
3. Type `:shell`.
4. A blank space will appear without any content.

**Expected behavior**
Correctly output "Hello from your shell" in Neovide

**Screenshots**

https://user-images.githubusercontent.com/1840653/225955975-5addaf4f-77db-4175-8cbb-f18e11cd75cd.mov

<br/>

**Logs**
The log is normal.

**Setup information**
- OS: MacOS Ventura 13.2.1
- Version: espanso 2.1.8
- Neovide: 0.10.3

**Comment by kopach** [comment]
Same happening for me, but in every app. I started to observe this behavior after upgrade to Ventura.
The only "triggers" which work – are those which use `force_clipboard: true` settings.
So, as temporary workaround - you might want to update your triggers with `force_clipboard: true`

For example:

```yml
  - trigger: ':date'
    force_clipboard: true
    replace: '{{mydate}}'
    vars:
      - name: mydate
        type: date
        params:
          format: '%m/%d/%Y'
```
