### ISSUE TITLE
Regex triggers fail to replace Unicode characters correctly

### ISSUE THREAD

**Issue by Hanaasagi** [espanso/espanso#1574]
**Describe the bug**

I'm using the regex triggers of espanso. When I try to use Unicode characters as content, they can be captured, but extra characters are removed during text replacement.

**To Reproduce**

```yaml
matches:
  - regex: "@\\((?P<p>.*?)\\)"
    replace: "{{output}}"
    vars:
      - name: output
        type: echo
        params:
          echo: "hello world"
```

**Screenshots**

https://user-images.githubusercontent.com/9482395/228489263-528363ec-f70b-4499-9978-42fecbe56087.mp4

*ext* is deleted.

**Expected behavior**

*ext* is not deleted.

**Logs**

No useful logs

**Setup information**
- OS: ArchLinux kernel 6.2.8-arch1-1 with Xorg 21.1.7
- Version: espanso 2.2.0 from AUR
