### ISSUE TITLE
Give us a guideline for specifying the PATH when using Script Extension.

### ISSUE THREAD

**Issue by nemonein** [espanso/espanso#1586]
**Setup information**
- OS: Archlinux
- Version: espanso 2.1.8 (AppImage)

---
Hi.
When using Script Extension, the conventional way of expressing the path does not work.
For example,

```
  - trigger: ":pysx"
    replace: "{{the_result}}"
    word: true
    vars:
      - name: the_result
        type: script
        params:
          args:
            - python
              #- "$HOME/bin/p_true.py"  # Err! python: can't open file '/home/narch/$HOME/bin/p_true.py': [Errno 2] No such file or directory
              #- "~/bin/p_true.py"  # Err! python: can't open file '/home/narch/$HOME/bin/p_true.py': [Errno 2] No such file or directory
              #- bin/p_true.py             # Works. bin means $HOME/bin
              #- "%HOME%/bin/p_true.py"       # Also works.
```

I could not find any document about this. All I've found one is how to use [%CONFIG%](https://espanso.org/docs/matches/extensions/#script-extension).
%HOME% was my rough guess, but it worked.

Can you describe this on the documentation please?
I want to know if there are any other wildcards.

Thank you for reading!
