### ISSUE TITLE
Clipboard backend inserts an extra newline with literal block scalar

### ISSUE THREAD

**Issue by swrobel** [espanso/espanso#1587]
**Describe the bug**
When using the [Literal Block Scalar](https://espanso.org/docs/matches/basics/#multi-line-expansions) `|` for multi-line expansions, an extra newline is inserted at the end. This does not occur with `\n`

**To Reproduce**
1. Create an expansion like so:
```yaml
  - trigger: :2lines
    replace: "two lines\nno more"
  - trigger: :2andmore
    replace: |
      two lines
      and more
```

**Expected behavior**
There should be a newline between the two lines, but not an extra one at the end, unless that's included as part of the replacement.

**Examples**
2lines:
```
two lines
no more
```

2andmore (note extra blank line):
```
two lines
and more

```

**Setup information**
- OS: macOS 13.3.1
- Version: 2.0.8

**Comment by federico-terzi** [comment]
Hey @swrobel,

I'm sorry you experienced this problem! IIRC, you should add a `-` after `|` if you don't want the extra line at the end

```yml
  - trigger: :2andmore
    replace: |-
      two lines
      and more
```

See: https://yaml-multiline.info/

Cheers :)
