### ISSUE TITLE
espanso not working on nautilus

### ISSUE THREAD

**Issue by ChristianNext** [espanso/espanso#1648]
**Describe the bug**
no expansion inside nautilus and gnome-text-editor
espanso works great in the terminal, Firefox, gedit, libreoffice

**To Reproduce**
1. type ":date" into nautilus search
2. nothing happens

**Expected behavior**
expand date to current date

**Screenshots**
**Logs**
nop change in log when expanding inside nautilus
10:37:47 [worker(3357)] [INFO] using X11AppInfoProvider
10:37:47 [worker(3357)] [INFO] using X11Source
10:37:47 [worker(3357)] [INFO] monitoring the status of the daemon process
10:37:47 [worker(3357)] [INFO] using X11Injector
10:37:49 [worker(3357)] [INFO] using X11Clipboard

**Setup information**
- OS: What OS are you using?
Ubuntu 23.04 with X11
- Version: which version of Espanso are you running? (you can find out by running `espanso --version` inside a terminal)
espanso 2.1.4-beta

**Comment by jwigg-netscout** [comment]
the most recent version of Espanso is 2.1.8; can you upgrade and try reproducing the issue then?

**Comment by ChristianNext** [comment]
Same issue on 2.2.0, installed via
`sudo snap install espanso --classic --channel=latest/edge`

**Comment by Vistaus** [comment]
Can confirm. I'm a KDE user, but just for you I installed gnome-text-editor to try and reproduce this and it fails for me too. Not just :date, but other expansions as well. I'm using the latest git dev branch, manually compiled on openSUSE Tumbleweed.

**Comment by jwigg-netscout** [comment]
just for fun, what happens if you make a per-app config for gnome-text-editor and set the replacement method to clipboard?

**Comment by ChristianNext** [comment]
Still cannot get espanso to work with nautilus, works for gnome-text-editor now.

I created ~/.config/espanso/config/nautilus.yml

```
filter_exec: nautilus
enable: true
matches:
 # Print the current date
  - trigger: ":date"
    replace: "{{mydate}}"
    vars:
      - name: :q!:mydate
        type: date
        params:
          format: "%Y-%m-%d  nautilus"
```

What else to make it work in nautilus on Ubuntu?

espanso 2.2.1

**Comment by smeech** [comment]
Firstly, are you using Espanso in Ubuntu X11? The Espanso Wayland implementation doesn't support app-specific configurations at all. If Wayland, just set up the trigger as below, but in a non-"_" prefixed match file. 

If X11, read on...

Your file mixes elements of `config` and `match` files, so it won't work in Espanso v2.
```yml
filter_class: Nautilus
enable: true # redundant
backend: clipboard # or inject or auto
includes: [../match/_nautilus.yml]
```
belong in an `espanso/config` file, although the `enable: true` is redundant as it's the default anyway. 

`filter_exec:` is mostly for Windows. In Linux, you'll find yourself using `filter_class:` mainly. Type `#detect#` in Nautilus to see the appropriate values (I don't have it here to check), and once up and running type `#acfg#` in Nautilus to see if it has picked up the config (rather than just `default.yml` - top line).
```yml
matches:
 # Print the current date
  - trigger: ":date"
    replace: "{{mydate}}"
    vars:
      - name: mydate
        type: date
        params:
          format: "%Y-%m-%d  nautilus"
```
belong in an `espanso/match/_nautilus.yml` file. I'm not sure what `:q!:` was for and you'll see a log error:
```
[ERROR] error during rendering: rendering error

Caused by:
    missing variable: `mydate`
```
because of it.

That having been said, I would test configuration and triggers separately, checking your trigger in a plain text editor first, and the simple `:espanso` trigger in Nautilus, and then your `:date` trigger.
