### ISSUE TITLE
false 'yyyy -mm-dd' date expansion

### ISSUE THREAD

**Issue by andrej1919** [espanso/espanso#1676]
**Describe the bug**
Please check these three examples:
```yaml
# three examples
  # 1. date formated as:                yyyy-mm-dd
  - name: date_eng
    type: date 
    params:
      format: "%Y-%m-%d"

  # 2. date formated as:                d. m. yyyy
  - name: date_slo
    type: date 
    params:
      format: "%-d. %-m. %Y"

  # 3. zettelkasten number formated as: yyyymmddhhmmss
  - name: zett
    type: date 
    params:
      format: "%Y%m%d%H%M%S"
```
Examples 2. and 3. work just fine, whereas example 1. fails if delimiter is hyphen character. It seems that it works just fine with any other character, only hyphen is ignored. Even if I replace `%-d. %-m. %Y` with `%F` the result is the same: `20230811` instead of `2023-08-11`

**To Reproduce**
1. Use three examples above and test replacing dot (Example 2.) with hyphen or inserting hyphen in Example 3. Hyphen is just ignored. This is the case everywhere (Kate, Dolphin, Emacs...) with a single exception: Alacritty terminal expands it correctly as `2023-08-11`.

**Expected behavior**
Get an expansion in a format `yyyy-mm-dd` anywhere in the system.

**Screenshots**
If applicable, add screenshots or screen recordings to help explain your problem.

**Logs**
I guess this is a problem:
`[worker(177006)] [WARN] char conversion error: invalid utf-8 sequence of 1 bytes from index 0`
However, it is strange that there is one place in a system (Alacritty terminal) where the date is expanded correctly.

**Setup information**
- OS:
```
Operating System: Manjaro Linux 
KDE Plasma Version: 5.27.6
KDE Frameworks Version: 5.108.0
Qt Version: 5.15.10
Kernel Version: 6.4.6-1-MANJARO (64-bit)
Graphics Platform: X11
```
- Version: `espanso 2.1.8`

**Comment by kpym** [comment]
For me on Windows it works fine. 
```yaml
  - trigger: ":test"
    replace: "{{date_eng}} {{date_slo}}"
    vars:
      - name: date_eng
        type: date
        params:
          format: "%Y-%m-%d"
      - name: date_slo
        type: date
        params:
          format: "%-d. %-m. %Y"
```
produce as expected `2023-12-17 17. 12. 2023` (today).
