### ISSUE TITLE
`$|$` causes a wrapping issue when next to a multiline text field

### ISSUE THREAD

**Issue by phorcys420** [espanso/espanso#1688]
**Describe the bug**
When using the following config, the multiline text field is wrapped improperly, which is causing a not-so-good experience when writing within the form

```yml
global_vars:
  - name: "fullname"
    type: "echo"
    params:
      echo: "John DOE"

matches:
  - trigger: ":mail"
    form: |
      Bonjour [[name]],

      [[body]]$|$
      
      [[politesse]],
      {{fullname}}
    form_fields:
      body:
        multiline: true
      politesse:
        type: choice
        default: Cordialement
        values:
          - Cordialement
          - Respectueusement
```

---

**To Reproduce**
1. Use the config
2. Run ``:mail``

**Expected behavior**
The multiline field is taking the full space it can, as such:

![espanso_proper](https://github.com/espanso/espanso/assets/57866459/2d7dcd07-6ab4-4e4e-baac-6cde8faa8a41)

---

**Screenshots**
![image](https://github.com/espanso/espanso/assets/57866459/a952dbf8-b164-4b7d-b07a-b89842d58e6a)
![espanso_improper](https://github.com/espanso/espanso/assets/57866459/6e32a6f3-9eb4-4861-8312-e4d3ac92550c)

---

**Setup information**
- OS: Windows 10 19045
- Version: 2.1.8
