### ISSUE TITLE
The inclusion of Chinese characters in the Script Extension will result in garbled text

### ISSUE THREAD

**Issue by Autumn-one** [espanso/espanso#1698]
**Describe the bug**
All the Chinese parts included in Python scripts are garbled

**To Reproduce**
Matching configuration is as follows
```yaml
matches:
    -   trigger: ":py"
        replace: "{{output}}"
        vars:
            -   name: output
                type: script
                params:
                    args:
                        -   python
                        -   "%CONFIG%/scripts/scripts.py"
```
scripts.py The contents are as follows
```python
import sys

if __name__ == "__main__":
    print(f"python 脚本参数:{sys.argv}")
```
**Screenshots**
![image](https://github.com/espanso/espanso/assets/26438145/20c0fbe5-53f4-48b7-a203-7028c2bcb587)

**Logs**
If possible, run `espanso log` in a terminal after the bug has occurred, then post the output here so that we can better diagnose the problem

**Setup information**
- OS: What OS are you using?
- Version: which version of Espanso are you running? (you can find out by running `espanso --version` inside a terminal)
- windows11 espanso 2.1.8
