### ISSUE TITLE
A trigger ":em" re-triggers when disable_x11_fast_inject is true -- possibly by prepending or leaving a colon

### ISSUE THREAD

**Issue by AndydeCleyre** [espanso/espanso#1701]
**Describe the bug**

With `disable_x11_fast_inject: true`, two problems are demonstrated with a trigger ":em":

- If ":em" matches to replacement "phooey", and ":phooey" is matched to "hello", typing ":em" will result in "hello" being pasted. Note there is no colon in the replacement text "phooey". This suggests that a colon is either added to the beginning of the output, pasting ":phooey" instead, or not getting properly deleted from the trigger name before pasting the replacement.

- If a trigger ":em" matches to replacement "emulate -L zsh", typing the trigger causes an infinite loop of pasting the replacement, as it apparently re-triggers in the process, each time. Again, an extra leading colon would explain this.

**To Reproduce**

`~/.config/espanso/config/default.yml`:
```yaml
disable_x11_fast_inject: true
```
`~/.config/espanso/match/base.yml`:
```yaml
matches:
  - trigger: ":em"
    replace: "phooey"
  - trigger: ":phooey"
    replace: "hello"
```

Type ":em", get "hello".

`~/.config/espanso/match/base.yml`:
```yaml
matches:
  - trigger: ":em"
    replace: "emulate -L zsh"
```
```console
$ sleep 4; espanso stop
```

Type ":em" and duck for cover.

**Expected behavior**

- In the first case, "phooey" should be pasted instead of "hello".

- In the second case, "emulate -L zsh" should be pasted only one time.

**Logs**
No log lines are added when these matches are triggered.

**Setup information**
- OS: Pop!_OS 22.04 LTS, with Plasma, X11
- Version: 2.1.8
