### ISSUE TITLE
Triple square brackets in form

### ISSUE THREAD

**Issue by Scartiloffista** [espanso/espanso#1744]
**Describe the bug**
I want to create a form with this format: `[[[var1]]][[[var2]]]...`

**To Reproduce**
1. add something like this to the conf
``` 
- trigger: ":r"
    form: |
      [[[project]]][[env]][[region]]
    form_fields:
      project:
        text:
      env:
        type: choice
        values:
          - production
          - staging
          - dev
      region:
        type: choice
        values:
          - eu-west-1
          - us-east-1
```

**Expected behavior**
A completion like `[project1][dev][eu-west-1]...`. The outermost [] should be ignored, but escaping or other stuff does not seem to work

**Screenshots**
![image](https://github.com/espanso/espanso/assets/36407154/76150e06-b92a-4a96-b3ff-814bfb8f1bfb)

**Logs**
```
11:40:48 [worker(48188)] [WARN] detected inconsistent modifier state for keys [(Meta, 55), (Control, 59), (Shift, 56)], sending compensating events...
11:40:51 [worker(48188)] [WARN] rendering was aborted by extension: form, on var: form1
```

**Setup information**
- OS: Mac OS 13.5.2
- Version: espanso 2.1.8

**Comment by smeech** [comment]
Does something like this give you the flexibility you're looking for, or have I misunderstood what you're trying to achieve?

```yml
matches:

  - trigger: ":r"
    replace: "[{{form1.project}}] [{{form1.env}}] [{{form1.region}}]"
    vars:
      - name: "form1"
        type: form
        params:
          layout: |
            [[project]] [[env]] [[region]]
          fields:
            project:
              text:
            env:
              type: choice
              values:
                - production
                - staging
                - dev
            region:
              type: choice
              values:
                  - eu-west-1
                  - us-east-1
```
