### ISSUE TITLE
Add the ability to "force timezone offset" to Date Extension

### ISSUE THREAD

**Issue by macintacos** [espanso/espanso#2186]
I would like to use the Date Extension to expand the current date/time as if my current timezone was converted to something else, like UTC. I know that you can specify a "locale", but I don't think that that allows you to output something like "UTC" when you use `%Z` (although if I'm wrong, please let me know!)

**Comment by AucaCoyan** [comment]
Mmm this makes a good candidate for a `espanso/hub` issue. I'll transfer the issue there!

**Comment by smeech** [comment]
The `date` extension is very limited - it doesn't even support {{variable}} offsets.
['chrono'](https://docs.rs/chrono/latest/chrono/format/strftime/index.html) is also limited, and is not aware of timezones beyond the local offset.
Currently, such a conversion needs to be scripted, ignoring Espanso's `date` extension entirely. Having played with this, I have versions in four different scripts in my [Pastebin](https://pastebin.com/8wy9dAU3), which are amenable to adjustments to use, for example, a `global_vars:` timezone offset.

**Comment by smeech** [comment]
```yml
matches:
  - trigger: :tzdate
    replace: '{{output}}'
    vars:
      - name: zones
        type: script
        params:
          args:
            - python
            - -c
            - |
              import pytz
              print("\n".join(pytz.all_timezones))
      - name: zone_choice
        type: form
        params:
          layout: 'Pick a time-zone: [[zone]]'
          fields:
            zone:
              type: list
              values: '{{zones}}'
              default: Europe/London
      - name: output
        type: script
        params:
          args:
            - python
            - -c
            - |
              import pytz; from datetime import datetime
              timezone = pytz.timezone('{{zone_choice.zone}}')
              # Get the current date and time in UTC
              utc_now = datetime.utcnow().replace(tzinfo=pytz.utc)
              # Convert UTC time to the specified timezone
              local_time = utc_now.astimezone(timezone)
              print("Current date and time in", timezone, "is:", local_time.strftime('%F %T'))
```
Not sure that it's worth a package.

It really does need to use an external library like Python `pytz` that keeps track of timezone names, daylight saving etc..
