### ISSUE TITLE
Form choice box labels and IDs won’t work when using controls with verbose syntax

### ISSUE THREAD

**Issue by bivoyo3035** [espanso/espanso#2263]
### Description

Defining a choice box with labels and IDs using the verbose syntax renders an empty list in the dialog window. Using plain list items works as expected.

### Steps to reproduce

```yml
yaml-language-server: $schema=https://raw.githubusercontent.com/espanso/espanso/dev/schemas/match.schema.json

imports:
  - ../global-vars/node.yml

matches:
  - trigger: ;cc
    replace: "{{output}}"
    vars:
      - name: input
        type: form
        params:
          layout: |
            Name: [[name]]
            Case: [[case]]
          fields:
            name:
              type: text
            case:
              type: choice
              values:
                - label: camelCase
                  id: camel-case
                - label: Capital Case
                  id: capital-case
                - label: CONSTANT_CASE
                  id: constant-case
                - label: dot.case
                  id: dot-case
                - label: kebab-case
                  id: kebab-case
                - label: no case
                  id: no-case
                - label: PascalCase
                  id: pascal-case
                - label: Pascal_Snake_Case
                  id: pascal-snake-case
                - label: path/case
                  id: path-case
                - label: Sentence case
                  id: sentence-case
                - label: snake_case
                  id: snake-case
                - label: Train-Case
                  id: train-case
                - label: sPoNGe CAse
                  id: sponge-case
                - label: sWAP cASE
                  id: swap-case
                - label: Title Case
                  id: title-case
      - name: output
        type: script
        params:
          args:
            - "{{node}}"
            - "%CONFIG%/scripts/change-case/index.mjs"
            - "{{input.name}}"
            - "{{input.case}}"
```

### Expected behavior

The `fields` parameter content to follow the same format as the `form_fields` parameter.

### Screenshots

With labels and IDs:

<img width="288" alt="Image" src="https://github.com/user-attachments/assets/08a67f08-ec02-429e-a820-96c35c9ba4a7" />

Without labels and IDs:

<img width="321" alt="Image" src="https://github.com/user-attachments/assets/f1c37770-d4c3-4659-abe2-93ceb8ec6c3c" />

### Your environment

- Operating system and version: **macOS 15.3.2**
- Espanso version: **2.2.1**

### Self-service

- [ ] I'd be willing to fix this bug myself.
