### ISSUE TITLE
Accept OS-specific variants in the ShellExtension

### ISSUE THREAD

**Issue by federico-terzi** [espanso/espanso#353]
This new enhancement would allow the user to specify different `cmd` commands based on the current OS.

**Comment by jmssmth** [comment]
Am piggybacking onto this. I'd love to have espanso replace my text-expanders on my remote machine (macOS) and my office machine (Win10), but for this to happen, I'd need the ability to specify different paths for scripts depending on the current OS.

And since I'm here, thanks for this excellent utility @federico-terzi!

**Comment by federico-terzi** [comment]
@jmssmth Thanks for the feedback! I'll try to prioritize it :)
In the meanwhile, you might be able to achieve the same goal with the steps described under "Script placement" https://espanso.org/docs/matches/#script-extension (although that would need to write the script in a cross-platform language, such as python)

Cheers :)

**Comment by jmssmth** [comment]
@federico-terzi thanks for pointing me to this. This will certainly help in some contexts. For my particular use case, when on different machines (OSes really) the path to the Python installation I need to use for various scripts is different. 

At a high level, maybe being able to designate the machine's hostname for particular groups of params/args: 

```yaml
- trigger: ":pyscript"
  replace: "{{output}}"
  vars:
    - name: output
      type: script
      params:
        - hostname: DPPFA32422  # windows machine
          args:
            - C:/Python385/python.exe
            - "%CONFIG%/scripts/script.py"
        - hostname: mac-mini-home  # macos machine
            args:
            - /usr/local/bin/python3.8
            - "%CONFIG%/scripts/script.py"
        - hostname: remote-linux-server  # linux machine
            args:
            - /home/linuxbrew/.linuxbrew/bin/python3  
            - "%CONFIG%/scripts/script.py"
```

Either way, thanks a ton for espanso! 

-J
