### ISSUE TITLE
Nested Matches Not Respecting Case

### ISSUE THREAD

**Issue by 4lch4** [espanso/espanso#374]
# Overview

When using a nested match, I've noticed it won't always respect the casing of the matches specified. For example, when accessing some local test servers I have a match for the username and one for the password. Instead of having to type them separately, I tried creating a single match that would combine the two, but it won't respect the casing for the password, causing the login to fail.

## Example

Here's a sample config that recreates the issue:

```yaml
name: secure
parent: default

matches:
  - trigger: ":jun"
    replace: "TestUserName"
  - trigger: ":jpw"
    replace: "TestPassword@!4"
  - trigger: ":ulg"
    replace: "{{UN}}\t{{PW}}"
    vars:
      - name: UN
        type: match
        params:
          trigger: ":jun"
      - name: PW
        type: match
        params:
          trigger: ":jpw"
```

Using the indidvidual `:jun` and `:jpw` matches will replace the text with the proper casing, but if I use the `:ulg` match, it's all in lowercase.

Am I doing something wrong or is this actually a bug?
