### ISSUE TITLE
Character Missing & Weird Action in VScode

### ISSUE THREAD

**Issue by ZXYFrank** [espanso/espanso#546]
Hey federico-terzi,

Here is my config file ('markdown.yml',Win 10)

```
name: markdown
parent: default
filter_title: "vnote"

matches:
  - trigger: "=dp"
    force_clipboard: true
    replace: "<details><summary>$|$</summary><img src = ''/></details>"

  - trigger: "=dd"  
    replace: "<details><summary>$|$</summary></details>"

  - trigger: "\\bold"
    replace: "\\boldsymbol{$|$}"

  - trigger: "=bf"
    replace: "<font size=\"5em\" face=\"Consolas\">$|$</font>"

  - trigger: "=et"
    replace: "<br />&emsp;&emsp;"

  - trigger: "=ee"
    replace: "<br />"

  - trigger: "==c1"
    replace: "<font color = red>{{clipboard}}$|$</font>"

  - trigger: "==c2"
    replace: "<font color = orange>{{clipboard}}$|$</font>"

  - trigger: "==c3"
    replace: "<font color = blue>{{clipboard}}$|$</font>"

  - trigger: "==c3"
    replace: "<font color = green>{{clipboard}}$|$</font>"

  - trigger: "=c1"
    replace: "<font color = red>$|$</font>"

  - trigger: "=c2"
    replace: "<font color = orange>$|$</font>"

  - trigger: "=c3"
    replace: "<font color = blue>$|$</font>"

  - trigger: "=c4"
    replace: "<font color = green>$|$</font>"

  - trigger: "=q"
    replace: "『***QUESTION***:**$|$?**』"

    
  - trigger: "=a"
    replace: "**『$|$』**"
  

global_vars:
  # - name: mydate
  #   type: date
  #   params:
  #     format: "%m/%d/%Y"
  - name: "clipboard"
    type: "clipboard"

```

_since it has been merged to the defalut one, filter seems to be useless. I know that._

----

**However, when typing in VScode, it seems that all of the expanding action will leave some characters.**

Specifically, chars of the same number as the "pattern"will be omitted.

**(I use the var clipboard)**

![GIF 2020-12-16 9-43-54](https://user-images.githubusercontent.com/49837632/102294190-b2534780-3f83-11eb-9a5e-1cc51118f70e.gif)

When pressing **Ctrl+Z** to undo, I can see some chars deleted(See the recoverd bracket **[]** in the GIF below). 

It seems like having been **pasted there one by one**.

Besides, there is something working well ("}|"->"「」")

![GIF 2020-12-16 9-45-09](https://user-images.githubusercontent.com/49837632/102294343-14ac4800-3f84-11eb-8a56-bf826397383c.gif)

Except for the suspectable flaws, thanks for your wonderful work. It really helps!
