### ISSUE TITLE
Form injection fails in full-screen mode

### ISSUE THREAD

**Issue by MacSteini** [espanso/espanso#562]
Working with the latest versions of Espanso and macOS.

### **Issue:**
Forms do not inject input into apps operating in full-screen mode.

### **Expected behaviour:**
The input shall be injected into the app from where the shortcut triggered the form.

### **Steps to reproduce:**
* Create a form trigger in default.yml, e. g. `form: "Hey {{name}},\nHappy Birthday!"`)
* Open an app in full-screen mode, e. g. TextEdit, create a new document and trigger the form with the respective shortcut
* When submitting the form, the respective input will not show up in TextEdit but somewhere else

**Comment by federico-terzi** [comment]
Hey @MacSteini,

Thanks for reporting this issue! Out of curiosity, do the normal matches (without form) work as expected when full screen?

Cheers :)

**Comment by MacSteini** [comment]
Yes, they do work either way. It's just the form feature that causes headache.

**Comment by federico-terzi** [comment]
@MacSteini I see, thank you. I'll investigate :)

**Comment by shriharip** [comment]
@federico-terzi Thanks for a wonderful project..

I am also facing this issue on macOS Catalina (10.15).. Not in full screen. Just the app. I tried deleting the modulo app inside application support and restarting and also enabling secure input.

Still form fields do not expand 

here is the config

````
 - trigger: ":email"
    form: |
      {{choices}}
    form_fields:
      choices:
        type: list
        values:
          - v1@gmail.com
          - v2@gmail.com
          - v3@gmail.com
          - v4@hotmail.com
````
It just adds a space after I click on Ctrl+Enter ( or submit)

cheers :)
