### ISSUE TITLE
Document date offset parameter

### ISSUE THREAD

**Issue by kahironimashte** [espanso/espanso#595]
Hi, how can I output the time for "now + 1 hour" or "today - 1 day"? 

So far I copied the example for now from the dokumentation:

- trigger: ":now"
  replace: "{{vnow}}"
  vars:
    - name: vnow
      type: date
      params:
        format: "%H:%M"

But it only lets me output the current date or time. Bot not e. g. tomorrow or "in one hour"

**Comment by federico-terzi** [comment]
Hey @kahironimashte,

You are looking for the `offset` parameter (which I just noticed isn't documented yet), that allows you to specify an offset in seconds. For example:

```yaml
  - trigger: ":yesterday"
    replace: "{{mytime}}"
    vars:
    - name: mytime
      type: date
      params:
        format: "%c"
        offset: -86400
  - trigger: ":nexthour"
    replace: "{{mytime}}"
    vars:
    - name: mytime
      type: date
      params:
        format: "%H:%M"
        offset: 3600
```

Cheers :)
