### ISSUE TITLE
What is the proper way to let user configure espanso plugin/package?

### ISSUE THREAD

**Issue by kopach** [espanso/espanso#653]
Hi. I've built the package for date manipulation https://github.com/kopach/espanso-package-date-utilities. Basically, it can return e.g. today's date by typing `:d0` and so on. By default, it produces date in the following format: `dd MMM yyyy`, e.g. `25 Apr 2021`. I would like to give users the possibility to configure the produced format. e.g., someone would like to have it like so: `🗓 dd/MM/yyyy`, which would produce string: `🗓 25/04/2021`. 

So, how can I achieve such configurability? Is there any official way to do so?

**Comment by federico-terzi** [comment]
Hey @kopach,

Thanks for your help! We are currently refactoring the package system so things will likely change in the upcoming releases.
A possible solution is currently used by this package: https://github.com/wressl/medical-docs
Basically, it tells the user to define a set of global variables and then uses them from the package snippets. You can also pass those variables to scripts (see the last example): https://espanso.org/docs/matches/#advanced-topics

Cheers :)

**Comment by kopach** [comment]
Hey @federico-terzi
Just had a chance to test this approach, and it seems like not applicable in my case. In case of https://github.com/kopach/espanso-package-date-utilities I'm using `node` script to calculate output. So, I need a way to pass a global variable as argument to that `node` script.

Something like this

```yml
global_vars:
  - name: 'dateUtilities_format'
    type: 'dummy'
    params:
      echo: '🗓 dd/MMM/yyyy'

matches:
  - trigger: ':d0'
    replace: '{{output}}'
    vars:
      - name: output
        type: script
        params:
          args:
            - node
            - '%CONFIG%/user/espanso-package-date-utilities/date-utilities/1.0.0/dist/index.js'
            - 'd0'
            - '{{dateUtilities_format}}'
```

doesn't actually work. 
In that `node` script I'm getting the second argument literally as `'{{dateUtilities_format}}'` string instead of `'🗓 dd/MMM/yyyy'`. So, `'{{dateUtilities_format}}'` doesn't actually get "converted" to `'🗓 dd/MMM/yyyy'` by `espanso` in this case.

Any ideas how to make it work? Or any other suggestions how to allow user input some configurability into options for https://github.com/kopach/espanso-package-date-utilities?
