### ISSUE TITLE
Tigger is not being replaced

### ISSUE THREAD

**Issue by mbaierl** [espanso/espanso#712]
For some triggers the trigger itself is not replaced.

For example:
```  
 - trigger: "today;"
    replace: "{{mydate}}"
    vars:
      - name: mydate
        type: date
        params:
          format: "%d.%m.%Y"
          
  - trigger: ":today"
    replace: "{{mydate}}"
    vars:
      - name: mydate
        type: date
        params:
          format: "%d.%m.%Y"
```

`:today` works fine and is replaced with the current date.
`today;` does not work and prints out `today;25.07.2021`

I tried various triggers and none of them works if the : or ; is at the end of the trigger word. 

Why is that and how can it be fixed?
