### ISSUE TITLE
Force clipboard replaces the trigger with `v`

### ISSUE THREAD

**Issue by revolter** [espanso/espanso#746]
For example, having this:
```yaml
matches:
  - trigger: "@bug"
    replace: |-
      first
      second
    force_clipboard: true
```
causes `@bug` to be replaced with `v`, and the cursor to the left of it on macOS 11.5.2 (20G95).
