### ISSUE TITLE
Missing/possibly double characters in certain text/search fields

### ISSUE THREAD

**Issue by MostHated** [espanso/espanso#750]
Hey there,
I have been having an issue with certain text fields, namely, the github search field. I used to use the app 'Albert' to do my expansion, but I use github search so much that it's issues caused me to look for a new solution simply to help with that. 

I am not sure what it was about AutoHotKey on Windows, but I almost never had an issue with it when using it's 'hotstrings', so I am not sure if it's timing or what it is. I really like espanso, so I am hoping that maybe there is something I can tweak to help with this. I tried my best to capture an "in action" example in the clip below.

I don't really know what all can be done about it, I am guessing it is mostly due to the delay in the search box, but it is annoying enough when it happens, and it happens often enough, that I usually just end up typing it all out anyway, because I have to backtrack to fix it half the time. I know for sure it's not espanso's fault, and probably not its job to account for delays in the application you are trying to type to.

I appreciate any suggestions anyone might have. I do try to mitigate it by going to a separate bookmark I have to a dedicated search page, but I only remember to do that every so often.

(Seen here, it doesn't happen all the time, but sometimes there will be multiple first characters, and occasionally something missing from the middle area)
![missing](https://user-images.githubusercontent.com/3442753/132076283-cda5eb00-d779-4833-8229-ffe2c205a0bb.gif)

Example expansions:

```yaml
  - trigger: "la:sh"
    replace: "language:shell"
  - trigger: "la:cs"
    replace: "language:csharp"
  - trigger: "la:da"
    replace: "language:dart"
  - trigger: "la:ps"
    replace: "language:powershell"
  - trigger: "la:py"
    replace: "language:python"
  - trigger: "pu:20"
    replace: "pushed:>2020-01-01"
  - trigger: "cr:20"
    replace: "created:>2020-01-01"
  - trigger: "pu:21"
    replace: "pushed:>2021-01-01"
  - trigger: "cr:21"
    replace: "created:>2021-01-01"
```

**Comment by federico-terzi** [comment]
Hey @MostHated,

I'm sorry you experienced this problem! As you said, this is likely a timing problem. Two possible approaches could be to:

1. Use `force_clipboard: true` and see if that helps:

```yaml
  - trigger: "la:py"
    replace: "language:python"
    force_clipboard: true
```

2. Play with `backspace_delay` and `inject_delay` in your `default.yml` file:

```yaml
backspace_delay: 10
inject_delay: 10
```

Going as up as 1000. If you see this helps, you might then create an [app specific config](https://espanso.org/docs/configuration/#application-specific-configurations) to set it only for Chrome/Firefox

Cheers :)
