### ISSUE TITLE
Search Bar: Error when typing to filter list

### ISSUE THREAD

**Issue by archetyped** [espanso/espanso#934]
**Describe the bug**

Frequently (but not always) when attempting to filter the list of options in the search bar (e.g. when using the [Choice extension](https://espanso.org/docs/next/matches/extensions/#choice-extension)), an error will be triggered after a single key is pressed in the search bar's text field:

```
[Espanso]: An error occurred during rendering, please examine the logs for more information.
```

**To Reproduce**
1. Create a match using the Choice extension.
    Example:
    ```yml
      # Choice Test
      - triggers: [":test"]
        label: "Options List"
        replace: "{{selection}}"
        vars:
          - name: selection
            type: choice
            params:
              values:
                - label: "One"
                  id: "Oneoneone"
                - label: "Two"
                  id: "Twotwotwo"
                - label: "Three"
                  id: "Threethreethree"
                - label: "Four"
                  id: "Fourfourfour"
    ```
2. Trigger match.
3. Attempt to type text to filter the list of choices.
4. Error message is output.

**Note:** The error is triggered when using the search bar in general, but the Choice extension provides a more semi-consistent example that results in the error.

**Expected behavior**
Typing text in the search bar text field should filter the list without errors.

**Screenshots**
N/A

**Logs**

```
17:33:08 [worker(31374)] [WARN] rendering was aborted by extension: choice, on var: selection
17:33:10 [worker(31374)] [WARN] extension 'choice' on var: 'selection' reported an error: modulo returned an empty output
17:33:10 [worker(31374)] [ERROR] error during rendering: rendering error

Caused by:
    modulo returned an empty output
```

**Setup information**
- OS: macOS 12.1
- Version: 2.1.2-alpha
