### ISSUE TITLE
Support YAML merge key

### ISSUE THREAD

**Issue by archetyped** [espanso/espanso#954]
**Is your feature request related to a problem? Please describe.**
Support for the [merge key](https://yaml.org/type/merge.html) (`<<:`) in YAML files would reduce the amount of unnecessary and repetitive typing users need to do.  Seems right up Espanso's alley ;)

For example, merge key support would allow for creating base templates of forms, variables, parameters, etc. so that they can be reused throughout the config file, while still allowing for adjustment on a per-match basis.

**Describe the solution you'd like**
Support the merge key in Espanso's YAML config files.

**Additional context**

* [`yaml-merge-keys` crate](https://crates.io/crates/yaml-merge-keys) - adds support for merge keys for YAML documents to `yaml-rust` and `serde_yaml`.
* [YAML merge key specification](https://yaml.org/type/merge.html)
* Despite not being part of YAML 1.2 spec, merge keys are fairly widely supported by software that consumes YAML (Docker, Bitbucket, GitLab, etc).

**Comment by federico-terzi** [comment]
Hey @archetyped,

Thank you for the feedback! This looks interesting, though I'd personally prefer to stick to the YAML specification to maximize compatibility with existing tools.
A lot of those reusability concerns could be solved with [Variables](https://espanso.org/docs/next/matches/variables/), so I'd rather extend the limits of variables to support more use-cases rather than introduce an extension to the YAML format

Hope you'll understand :)

Cheers :)

**Comment by archetyped** [comment]
Variables are great, but they are quite verbose, requiring _at least_ 4 lines of YAML to define a single variable.

```yaml
- name: myvar
  type: echo
  params:
      echo: "Variable Value"
```

Merge key support would allow **multiple variables** to be set up once and reused across many matches with just **a single line**.  The main benefit over standard YAML aliases/anchors is that the merge key allows other matches to override specific variables to customize their output.

```yaml
- trigger: "tpl_form"
  label: "Form Template"
  replace: "{{output}}"
  vars: &form_template
    - name: myvar
      type: echo
      params:
          format: "Variable Value"
    - name: myform
      type: form
      params:
          # ...
    # ... more variables ...
    
- triggers: ["match1"]
  label: "Other Match"
  replace: "{{output}}"
  vars:
    <<: *form_template
    - name: myvar
      type: echo
      params: 
        echo: "Override default value"

- triggers: ["match2"]
  label: "Other Match"
  replace: "{{output}}"
  vars:
    <<: *form_template
    - name: myvar
      type: echo
      params: 
        echo: "Override default value in a different way"
```

I'm still getting started with Espanso, so it's definitely possible I'm missing some feature of variables, so I appreciate any insight you can offer on how variables could be used to similarly reuse blocks of variables and keep things as [DRY](https://en.wikipedia.org/wiki/Don%27t_repeat_yourself "Don't repeat yourself") as possible.

Thanks.

**Comment by federico-terzi** [comment]
@archetyped Good point, thanks! I agree variables are currently much more verbose than merge keys, and it's an area worth exploring. After the current priorities are sorted out, we can start working on that one :)

**Comment by NicolasWebDev** [comment]
Is there any news on that front @AucaCoyan ?

I understand that merge keys are more widely supported now.

It would indeed help quite a lot in DRYing out our files, especially when we make use of a lot of vars and shells.

**Comment by smeech** [comment]
I'm trying to get my head around this one.

We already have single line variables, e.g.:
```yml
global_vars:
  - { name: Clipb, type: clipboard }
```
and [Anchors & Aliases](https://espanso.org/docs/matches/extensions/#anchors-and-aliases), as @archetyped mentions, which _do_ allow multiple variables to be set up once and reused across many matches with just a single line.

I guess the essential difficulties are the verbose (and poorly named) `echo:` structure to define variables, and that triggers can't contain more than one variable of the same name, and therefore can't override, so:
```yml
anchors:
  - &variable1 { name: myvar, type: echo, params: { echo : "Variable Value" } }
  - &variable2 { name: myvar, type: echo, params: { echo : "Override variable Value" } } 
matches:
  - trigger: match1
    label: "Other Match"
    replace: "{{myvar}}"
    vars:
      - *variable1
      - *variable2
```
doesn't work, unless one of the last two lines is commented out.

I'm struggling to think of an example where this would be useful, however, and would be grateful for enlightenment!

**Comment by AucaCoyan** [comment]
Hi! first, thank you for asking, we (smeech and I) are so busy with the open issues that we don't usually look over the closed ones.

I've never used that feature in yaml, but I can see that there are interesting limits to walk forward. The hardest part (parsing the yaml correctly) is already solved by the library you mentioned, so we need to pipe it inside of espanso. It's _some_ work, but it's nowhere near as if we had to do it ourselves.

Reopening the issue! 🙌

**Comment by smeech** [comment]
I tried out YAML type-casting a few days ago, in the vain hope that `!!int` would type-cast the `date:` `offset:` parameter to allow it to use variables! Sadly not..

**Comment by NicolasWebDev** [comment]
Thanks for reopening this, @AucaCoyan!

@smeech, regarding your question about where this feature could be useful—I don’t recall the exact use case I had in mind, but here’s a simple example. It helps streamline the inclusion of a choice field across multiple forms, allowing users to override the default value when needed.

For instance, consider this YAML snippet:

```yaml
anchors:
  - &conditionally_include_section
    type: choice
    default: true
    values:
      - 'false'
      - 'true'

vars:
  - name: form
    type: form
    params:
      layout: |
        Name: [[name]]
        Company: [[company]]
        Offer to sign NDA? [[nda_boolean]]
      fields:
        nda_boolean:
          <<: *conditionally_include_section
          default: 'false'
```

More broadly, enabling the use of merge keys empowers users to create reusable components that can be injected into different parts of the YAML structure. Users can override specific values as needed, making configurations more flexible and maintainable.

In essence, and as far as I know, this approach is the closest YAML can get to templating functions. Instead of calling something like:
```yaml
templating_function(the_often_changing_parameter="other_value")
```

You would achieve the same effect in YAML with:
```yaml
<<: templating_function
fields:
  the_often_changing_parameter: "other_value"
```

Let me know if you’d like further clarification!
