### ISSUE TITLE
Not using my default Python version

### ISSUE THREAD

**Issue by ytechie** [espanso/espanso#964]
**Describe the bug**
Using espanso v 2.1.3-alpha

I have a script that is for Python 3. On Windows, only python 3 is installed, so it works great. On MacOS, the default is Python 2, so the script fails. I did create a symbolic link so that my python version is 3, but espanso is still using version 2.

I'm a little leery of changing the default version of Python for the entire MacOS system.

**To Reproduce**
1. Create a symbolic link so that python in terminal uses v3 by default: `sudo ln -s -f /opt/homebrew/bin/python3 /usr/local/bin/python`
2. Create a python 3 script (can just spit out the version, for example)
3. Have espanso run the script and it will run Python v2

**Expected behavior**
I expected it to use **my** default python version, or at least give me a way to specify the version.

**Setup information**
- OS: MacOS 12.3
- Version: 2.1.3-alpha

**Comment by federico-terzi** [comment]
Hey @ytechie,

I'm sorry you experienced this problem! Have you considered using the absolute path for python? Something like:

```yaml
  - trigger: ":pyscript"
    replace: "{{output}}"
    vars:
      - name: output
        type: script
        params:
          args:
            - /opt/homebrew/bin/python3
            - /path/to/your/script.py
```

Cheers :)

**Comment by ytechie** [comment]
Thanks for the quick response. Love espanso.

Unfortunately, that doesn't work in my scenario. I sync my entire config between a windows and a mac machine and use it on both. If I add in the full path, it will fix my Mac but break my PC.

**Comment by federico-terzi** [comment]
@ytechie I see, thanks! I've opened an issue to introduce a feature which would solve these use-cases #968.

In the meanwhile, you could create two different matches with windows and mac specific triggers, or use the same one, which will trigger [Match disambiguation](https://espanso.org/docs/next/matches/basics/#match-disambiguation)

I know it's not ideal, but we'll work on that :)

**Comment by federico-terzi** [comment]
Also, once we solve #966 this one might be good to go as well :)

**Comment by smeech** [comment]
> @ytechie I see, thanks! I've opened an issue to introduce a feature which would solve these use-cases #968.
> 
> In the meanwhile, you could create two different matches with windows and mac specific triggers, or use the same one, which will trigger [Match disambiguation](https://espanso.org/docs/next/matches/basics/#match-disambiguation)
> 
> I know it's not ideal, but we'll work on that :)

Or have machine-specific `include:` files _outside_ Espanso $CONFIG, each containing a global variable for the local Python path, and use that variable within the trigger.

**Comment by AucaCoyan** [comment]
Tried with the latest version, and it works correctly 👍🏼 .
```bash
# install uv from https://docs.astral.sh/uv/getting-started/installation/
uv python install
# make the symlink
sudo ln -s -f  /Users/username/.local/share/uv/python/cpython-3.13.1-macos-aarch64-none/bin/python /usr/local/bin/python
```

```python
# ~/repos/main.py script
import sys

print(sys.version) # prints the python version
```

```yaml
  - trigger: ":pyscript"
    replace: "{{output}}"
    vars:
      - name: output
        type: script
        params:
          args:
            - /usr/local/bin/python
            - /Users/username/repos/main.py
```

watch out the `username` completion

and
```
:pyscript
3.13.1 (main, Jan 14 2025, 23:31:50) [Clang 19.1.6 ]
```
🎉
